-- Insert all regimes from Excel file with descriptions
-- Format: category + digit1 + digit2 = code (e.g., C+1+00 = C100)

-- First, delete existing regimes to reimport clean data
DELETE FROM public.customs_regimes;

-- C1XX - Mise à la consommation suite importation directe PNP
INSERT INTO public.customs_regimes (code, category, name, use_case, keywords, dd, stx, rs, tin, tva, cosec, pcs, pcc, tpast, ta) VALUES
('C100', 'C', 'MISE A LA CONSOMMATION EN SUITE IMPORTATION DIRECTE PNP', 'Importation définitive de produits non pétroliers pour mise en consommation locale', ARRAY['importation', 'directe', 'consommation', 'PNP', 'standard', 'normale', 'régime commun'], true, true, true, true, true, true, true, true, true, true),
('C101', 'C', 'MISE CONSOMMATION AVEC RESTITUTION DE DROITS PERÇUS PRIME AB', 'Importation avec restitution de droits pour réexportation', ARRAY['restitution', 'droits', 'prime', 'AB'], true, true, true, true, true, true, true, true, true, true),
('C102', 'C', 'MISE A LA CONSOMMATION DE PNP (DRAWBACK) SUITE IMP.DIRECTE', 'Régime drawback pour importation de matières premières transformées puis réexportées', ARRAY['drawback', 'transformation', 'réexportation', 'matières premières'], true, true, true, true, true, true, true, true, true, true),
('C111', 'C', 'MISE CONSOMMATION SUITE IMPORT DIRECTE DONS AIDES A L''ETAT', 'Dons et aides destinés à l''État sénégalais', ARRAY['dons', 'aides', 'état', 'gouvernement', 'humanitaire'], false, false, false, false, false, false, false, false, false, false),
('C112', 'C', 'MISE CONSOMMATION SUITE IMPORT DIRECTE DONS A CROIX ROUGE', 'Dons pour la Croix-Rouge et œuvres de bienfaisance', ARRAY['croix-rouge', 'bienfaisance', 'humanitaire', 'ONG', 'charitable'], false, false, false, false, false, false, false, false, false, false),
('C113', 'C', 'MISE CONSOMMATION DONS AIDES A CARACTERE SOCIAL PNP', 'Dons à caractère social ou culturel', ARRAY['social', 'culturel', 'dons', 'aides', 'ONG'], false, false, false, false, false, false, false, false, false, false),
('C121', 'C', 'MISE CONSOMMATION FRANCHISE EXCEPTIONNELLE SUITE IMP DIRECTE', 'Franchise exceptionnelle accordée par décision spéciale', ARRAY['franchise', 'exceptionnelle', 'exonération', 'spéciale'], false, false, true, false, false, true, true, true, false, false),
('C122', 'C', 'FRANCHISE CONDITIONNELLE SUITE IMPORTATION DIRECTE DE PNP', 'Franchise conditionnelle avec engagement spécifique', ARRAY['franchise', 'conditionnelle', 'engagement'], false, false, true, false, false, true, true, true, false, false),
('C123', 'C', 'DEMENAGEMENTS', 'Effets de déménagement pour particuliers', ARRAY['déménagement', 'effets personnels', 'particulier', 'retour', 'expatrié'], false, false, true, false, false, true, true, true, false, false),
('C124', 'C', 'EFFETS PERSONNELS', 'Effets personnels des voyageurs', ARRAY['effets personnels', 'voyageur', 'particulier', 'bagages'], false, false, true, false, false, true, true, true, false, false),
('C125', 'C', 'REIMPORTATION MARCH.SENEGAL DEFECT.OU NON CONF A COMMANDE', 'Réimportation de marchandises défectueuses ou non conformes', ARRAY['réimportation', 'défectueux', 'non conforme', 'retour', 'réclamation'], false, false, true, false, false, true, true, true, false, false),
('C126', 'C', 'DECLARATION ENLEVEMENT SPECIAL (D.E.S) YOFF', 'Déclaration enlèvement spécial aéroport Yoff', ARRAY['DES', 'aéroport', 'Yoff', 'enlèvement', 'spécial', 'aérien'], true, true, true, true, true, true, true, true, true, true),
('C131', 'C', 'FRANCHISE TOTALE AU TITRE DU CODE DES INVESTISSEMENTS', 'Investissement agréé avec franchise totale', ARRAY['investissement', 'code investissement', 'franchise totale', 'agréé', 'exonération'], false, false, true, false, false, true, true, true, false, false),
('C132', 'C', 'IAL - IMPORTATION AVANT LIQUIDATION', 'Importation avant liquidation pour entreprises', ARRAY['IAL', 'liquidation', 'entreprise'], true, true, true, true, true, true, true, true, true, true),
('C133', 'C', 'REGIME STABILISE', 'Régime fiscal stabilisé pour investisseurs', ARRAY['stabilisé', 'fiscal', 'investissement', 'convention'], true, false, true, false, true, true, true, true, false, false),
('C134', 'C', 'EXONERATION PARTIELLE TVA SUITE IMPORTATION DIRECTE PNP', 'Exonération partielle de TVA uniquement', ARRAY['TVA', 'exonération partielle', 'taxe'], true, true, true, true, false, true, true, true, true, true),
('C138', 'C', 'SUSPENSION PROVISOIRE DES DROITS ET TAXES', 'Suspension temporaire des droits pour situation exceptionnelle', ARRAY['suspension', 'provisoire', 'temporaire', 'crise'], false, false, false, false, false, false, false, false, false, false),
('C139', 'C', 'MISE A CONSOMMATION DS LE CADRE NOUVEAU CODE INVESTISSEMENT', 'Nouveau code des investissements', ARRAY['nouveau code', 'investissement', 'agréé'], false, false, true, false, false, true, true, true, false, false),
('C140', 'C', 'PRIVILEGE DIPLOMATIQUE', 'Franchise diplomatique pour ambassades et missions', ARRAY['diplomatique', 'ambassade', 'mission', 'consul', 'immunité'], false, false, false, false, false, false, false, false, false, false),
('C190', 'C', 'LIQUIDATION SUPPLEMENTAIRE', 'Régularisation de droits insuffisamment perçus', ARRAY['liquidation', 'supplémentaire', 'régularisation', 'redressement'], true, true, true, true, true, true, true, true, true, true),

-- C2XX - Mise à la consommation PP (Produits Pétroliers)
('C201', 'C', 'MISE A LA CONSOMMATION SUITE IMPORT DIRECTE COMMUN PP', 'Importation directe de produits pétroliers', ARRAY['pétrole', 'pétrolier', 'carburant', 'hydrocarbures', 'PP'], true, true, true, true, true, true, true, true, true, true),
('C202', 'C', 'MISE A LA CONSOMMATION SUITE IMPORT.DIRECTE DE PP/AVAL SAR', 'Produits pétroliers raffinerie SAR', ARRAY['SAR', 'raffinerie', 'pétrole', 'pétrolier'], true, true, true, true, true, true, true, true, true, true),
('C210', 'C', 'MISE CONSOMMATION SUITE IMPORT DIRECTE DONS CARACT SOCI PP', 'Dons produits pétroliers caractère social', ARRAY['dons', 'PP', 'social', 'pétrolier'], false, false, false, false, false, false, false, false, false, false),
('C211', 'C', 'MISE CONSOMMATION SUITE IMPORT DIRECTE DONS AIDES ETAT PP', 'Dons produits pétroliers à l''État', ARRAY['dons', 'état', 'PP', 'pétrolier'], false, false, false, false, false, false, false, false, false, false),
('C220', 'C', 'AU TITRE DES ADMISSIONS EXCEPTIONNELLES EN FRANCHISE', 'Admission exceptionnelle franchise PP', ARRAY['admission', 'exceptionnelle', 'franchise', 'PP'], false, false, true, false, false, true, true, true, false, false),
('C221', 'C', 'ADMISSION EXCEPTIONNELLE SUITE IMP DIRECTE DE PP', 'Admission exceptionnelle produits pétroliers', ARRAY['admission', 'exceptionnelle', 'PP', 'pétrolier'], false, false, true, false, false, true, true, true, false, false),
('C222', 'C', 'ADMISSION CONDITIONNELLE', 'Admission conditionnelle PP', ARRAY['admission', 'conditionnelle', 'PP'], false, false, true, false, false, true, true, true, false, false),
('C231', 'C', 'FRANCHISE TOTALE AU TITRE DU CODE DES INVESTISSEMENTS PP', 'Investissement franchise totale PP', ARRAY['investissement', 'franchise', 'PP', 'pétrolier'], false, false, true, false, false, true, true, true, false, false),
('C232', 'C', 'FRANCHISE PARTIELLE AU TITRE DU CODE DES INVESTISSEMENTS', 'Investissement franchise partielle', ARRAY['investissement', 'franchise partielle'], true, false, true, false, true, true, true, true, false, false),
('C233', 'C', 'REGIMES STABILISES', 'Régime stabilisé PP', ARRAY['stabilisé', 'PP', 'pétrolier'], true, false, true, false, true, true, true, true, false, false),
('C234', 'C', 'EXONERATION PARTIELLE TVA SUITE IMPORT DIRECTE PP', 'Exonération TVA PP', ARRAY['TVA', 'exonération', 'PP'], true, true, true, true, false, true, true, true, true, true),
('C238', 'C', 'SUSPENSION PROVISOIRE DES DROITS & TAXES', 'Suspension droits PP', ARRAY['suspension', 'PP', 'pétrolier'], false, false, false, false, false, false, false, false, false, false),
('C239', 'C', 'MISE CONSOMMATION DIRECTE DE PP NOUVEAU CODE INVESTISSEMENTS', 'Nouveau code investissement PP', ARRAY['nouveau code', 'investissement', 'PP'], false, false, true, false, false, true, true, true, false, false),
('C240', 'C', 'AU TITRE DES PRIVILEGES DIPLOMATIQUES', 'Privilège diplomatique PP', ARRAY['diplomatique', 'PP', 'pétrolier'], false, false, false, false, false, false, false, false, false, false),
('C290', 'C', 'LIQUIDATION SUPPLEMENTAIRE PP', 'Liquidation supplémentaire PP', ARRAY['liquidation', 'PP'], true, true, true, true, true, true, true, true, true, true),

-- C3XX - Suite entrepôt PNP
('C300', 'C', 'REGIME COMMUN', 'Régime commun entrepôt', ARRAY['entrepôt', 'commun'], true, true, true, true, true, true, true, true, true, true),
('C301', 'C', 'MISE A LA CONSOMMATION EN SUITE D''ENTREPOT PNP', 'Sortie d''entrepôt pour mise à la consommation', ARRAY['entrepôt', 'stockage', 'sortie', 'PNP'], true, true, true, true, true, true, true, true, true, true),
('C302', 'C', 'MISE A LA CONSOMMATION EN SUITE D''ENTREPOT APRES AT', 'Sortie entrepôt après admission temporaire', ARRAY['entrepôt', 'admission temporaire', 'AT', 'transformation'], true, true, true, true, true, true, true, true, true, true),
('C303', 'C', 'MISE CONSOMMATION SUITE ENTREPOT INDUSTRIEL DE PNP', 'Sortie entrepôt industriel PNP', ARRAY['entrepôt', 'industriel', 'PNP'], true, true, true, true, true, true, true, true, true, true),
('C304', 'C', 'MISE CONSOMMAT.SUITE ENTREPOT INDUST.REGLEMNT 004/2000 UEMOA', 'Règlement UEMOA entrepôt', ARRAY['UEMOA', 'entrepôt', 'industriel'], true, true, true, true, true, true, true, true, true, true),
('C311', 'C', 'DONS & AIDES DE PNP SUITE ENTREPOT DESTINES A L''ETAT', 'Dons État suite entrepôt', ARRAY['dons', 'état', 'entrepôt'], false, false, false, false, false, false, false, false, false, false),
('C312', 'C', 'DESTINES A LA CROIX-ROUGE ET AUX OEUVRES DE BIENFAISANCE', 'Dons Croix-Rouge suite entrepôt', ARRAY['croix-rouge', 'bienfaisance', 'entrepôt'], false, false, false, false, false, false, false, false, false, false),
('C313', 'C', 'DONS AIDES PR ORGANISME A CARACTERE CULTUREL OU SOCIAL', 'Dons social/culturel entrepôt', ARRAY['social', 'culturel', 'dons', 'entrepôt'], false, false, false, false, false, false, false, false, false, false),
('C321', 'C', 'FRANCHISE EXCEPTIONNELLE SUITE ENTREPOT DE PNP', 'Franchise exceptionnelle entrepôt', ARRAY['franchise', 'exceptionnelle', 'entrepôt'], false, false, true, false, false, true, true, true, false, false),
('C322', 'C', 'FRANCHISE CONDITIONNELLE SUITE D''ENTREPOT DE PNP', 'Franchise conditionnelle entrepôt', ARRAY['franchise', 'conditionnelle', 'entrepôt'], false, false, true, false, false, true, true, true, false, false),
('C331', 'C', 'FRANCHISE TOTALE TITRE CODE INVEST. SUITE ENTREPOT DE PNP', 'Investissement franchise entrepôt', ARRAY['investissement', 'franchise', 'entrepôt'], false, false, true, false, false, true, true, true, false, false),
('C332', 'C', 'TAXATION PARTIELLE TITRE CODE INVEST. SUITE ENTREPOT DE PNP', 'Investissement taxation partielle entrepôt', ARRAY['investissement', 'partiel', 'entrepôt'], true, false, true, false, true, true, true, true, false, false),
('C333', 'C', 'REGIME STABILISE SUITE ENTREPOT DE PNP', 'Régime stabilisé entrepôt', ARRAY['stabilisé', 'entrepôt'], true, false, true, false, true, true, true, true, false, false),
('C334', 'C', 'EXONERATION PARTIELLE TVA SUITE ENTREPOT', 'Exonération TVA entrepôt', ARRAY['TVA', 'exonération', 'entrepôt'], true, true, true, true, false, true, true, true, true, true),
('C338', 'C', 'DROIT SUSPEND SORTIE ENTREPOT', 'Droit suspendu sortie entrepôt', ARRAY['suspension', 'entrepôt'], false, false, false, false, false, false, false, false, false, false),
('C339', 'C', 'MISE CONSOMMATION SUITE ENTREPOT NOUVEAU CODE INVESTISSEMENT', 'Nouveau code investissement entrepôt', ARRAY['nouveau code', 'investissement', 'entrepôt'], false, false, true, false, false, true, true, true, false, false),
('C340', 'C', 'FRANCHISE DIPLOMATIQUE SUITE ENTREPOT DE PNP', 'Diplomatique entrepôt', ARRAY['diplomatique', 'entrepôt'], false, false, false, false, false, false, false, false, false, false),
('C380', 'C', 'REGULARISATION AVITAILLEMENTS NAVIRES', 'Régularisation avitaillement', ARRAY['avitaillement', 'navires', 'régularisation'], true, true, true, true, true, true, true, true, true, true),
('C390', 'C', 'LIQUIDATION SUPPLEMENTAIRE', 'Liquidation supplémentaire entrepôt', ARRAY['liquidation', 'entrepôt'], true, true, true, true, true, true, true, true, true, true),
('C399', 'C', 'MISE A CONSOMMAT.SUITE ENTREPOT D''EMBALLAGES FABRIQUES EN AT', 'Emballages AT entrepôt', ARRAY['emballages', 'AT', 'entrepôt'], true, true, true, true, true, true, true, true, true, true),

-- C4XX - Suite entrepôt PP
('C400', 'C', 'MISE CONSOM.DE PP SUITE ENTREPOT OU USINE EXERCEE', 'Entrepôt/usine PP', ARRAY['entrepôt', 'usine', 'PP', 'pétrolier'], true, true, true, true, true, true, true, true, true, true),
('C401', 'C', 'MISE A LA CONSOMMATION EN SUITE D''ENTREPOT DE PP', 'Entrepôt PP', ARRAY['entrepôt', 'PP', 'pétrolier'], true, true, true, true, true, true, true, true, true, true),
('C402', 'C', 'MISE A LA CONSOMMATION EN SUITE D''ENTREPOT DE PP', 'Entrepôt PP 2', ARRAY['entrepôt', 'PP'], true, true, true, true, true, true, true, true, true, true),
('C403', 'C', 'MISE CONSOMMATION SUITE ENTREPOT APRES AT DE PP', 'Entrepôt AT PP', ARRAY['entrepôt', 'AT', 'PP'], true, true, true, true, true, true, true, true, true, true),
('C405', 'C', 'MISE A LA CONSOMMATION PP MATIERE PREMIERE', 'Matière première PP', ARRAY['matière première', 'PP', 'pétrolier'], true, true, true, true, true, true, true, true, true, true),
('C410', 'C', 'DONS ET AIDES SUITE ENTREPOT DE PP', 'Dons entrepôt PP', ARRAY['dons', 'entrepôt', 'PP'], false, false, false, false, false, false, false, false, false, false),
('C421', 'C', 'FRANCHISE EXCEPTIONNELLE SUITE ENTREPOT DE PP', 'Franchise exceptionnelle entrepôt PP', ARRAY['franchise', 'exceptionnelle', 'entrepôt', 'PP'], false, false, true, false, false, true, true, true, false, false),
('C422', 'C', 'FRANCHISE CONDITIONNELLE SUITE D''ENTREPOT DE PP', 'Franchise conditionnelle entrepôt PP', ARRAY['franchise', 'conditionnelle', 'entrepôt', 'PP'], false, false, true, false, false, true, true, true, false, false),
('C424', 'C', 'AVITAILLEMENTS DES NAVIRES SENEGALAIS SUITE CONSIGNATION', 'Avitaillement navires sénégalais', ARRAY['avitaillement', 'navires', 'sénégalais'], false, false, true, false, false, true, true, true, false, false),
('C425', 'C', 'AVITAILLEMENT BATEAUX PECHE SENEGALAIS EN SOUTES NATIONAL', 'Avitaillement pêche', ARRAY['avitaillement', 'pêche', 'soutes'], false, false, true, false, false, true, true, true, false, false),
('C431', 'C', 'FRANCHISE TOTALE TITRE CODE INVEST.SUITE ENTREPOT DE PP', 'Investissement franchise entrepôt PP', ARRAY['investissement', 'franchise', 'entrepôt', 'PP'], false, false, true, false, false, true, true, true, false, false),
('C432', 'C', 'TAXATION PARTIELLE TITRE CODE INVEST.SUITE ENTREPOT DE PP', 'Investissement partiel entrepôt PP', ARRAY['investissement', 'partiel', 'entrepôt', 'PP'], true, false, true, false, true, true, true, true, false, false),
('C433', 'C', 'REGIME STABILISE SUITE ENTREPOT DE PP', 'Stabilisé entrepôt PP', ARRAY['stabilisé', 'entrepôt', 'PP'], true, false, true, false, true, true, true, true, false, false),
('C434', 'C', 'EXONERATION PARTIELLE TVA SUITE ENTREPOT PP', 'Exonération TVA entrepôt PP', ARRAY['TVA', 'exonération', 'entrepôt', 'PP'], true, true, true, true, false, true, true, true, true, true),
('C438', 'C', 'DROIT SUSPENDU SUITE ENTREPOT', 'Droit suspendu entrepôt PP', ARRAY['suspension', 'entrepôt', 'PP'], false, false, false, false, false, false, false, false, false, false),
('C439', 'C', 'MISE CONSOMMATION DE PP SUITE ENTREPOT NVEAU CODE INVEST', 'Nouveau code investissement entrepôt PP', ARRAY['nouveau code', 'investissement', 'entrepôt', 'PP'], false, false, true, false, false, true, true, true, false, false),
('C440', 'C', 'FRANCHISE DIPLOMATIQUE SUITE ENTREPOT DE PP', 'Diplomatique entrepôt PP', ARRAY['diplomatique', 'entrepôt', 'PP'], false, false, false, false, false, false, false, false, false, false),
('C450', 'C', 'REGULARISATION TAXE SUR LE PETROLE BRUT', 'Régularisation pétrole brut', ARRAY['régularisation', 'pétrole', 'brut'], true, true, true, true, true, true, true, true, true, true),
('C480', 'C', 'REGULARISATION AVITAILLEMENT NAVIRES EN PRODUITS PETROLIERS', 'Régularisation avitaillement PP', ARRAY['régularisation', 'avitaillement', 'PP'], true, true, true, true, true, true, true, true, true, true),
('C490', 'C', 'LIQUIDATION SUPPLEMENTAIRE', 'Liquidation entrepôt PP', ARRAY['liquidation', 'entrepôt', 'PP'], true, true, true, true, true, true, true, true, true, true),

-- C5XX - Suite AT
('C500', 'C', 'CONSOMMATION SUITE AT (REGIME COMMUN)', 'Régime commun AT', ARRAY['AT', 'admission temporaire', 'commun'], true, true, true, true, true, true, true, true, true, true),
('C501', 'C', 'MISE A LA CONSOMMATION SUITE AT EXCEPTIONNELLE', 'AT exceptionnelle', ARRAY['AT', 'admission temporaire', 'exceptionnelle'], true, true, true, true, true, true, true, true, true, true),
('C502', 'C', 'MISE CONSOM.SUITE AT POUR PERFECTIONNEMENT ACTIF', 'Perfectionnement actif', ARRAY['AT', 'perfectionnement actif', 'transformation'], true, true, true, true, true, true, true, true, true, true),
('C503', 'C', 'MISE A LA CONSOMMATION EN SUITE AT SPECIALE', 'AT spéciale', ARRAY['AT', 'admission temporaire', 'spéciale'], true, true, true, true, true, true, true, true, true, true),
('C504', 'C', 'MISE A CONSOMMATION SUITE ATN REGLEMENT 04/2000 UEMOA', 'ATN UEMOA', ARRAY['ATN', 'UEMOA', 'AT'], true, true, true, true, true, true, true, true, true, true),
('C511', 'C', 'DESTINES A L''ETAT', 'Dons État AT', ARRAY['dons', 'état', 'AT'], false, false, false, false, false, false, false, false, false, false),
('C512', 'C', 'DESTINES A LA CROIX-ROUGE ET AUX OEUVRES DE BIENFAISANCE', 'Dons Croix-Rouge AT', ARRAY['croix-rouge', 'bienfaisance', 'AT'], false, false, false, false, false, false, false, false, false, false),
('C513', 'C', 'A CARACTERE CULTUREL ET SOCIAL', 'Dons social AT', ARRAY['social', 'culturel', 'AT'], false, false, false, false, false, false, false, false, false, false),
('C521', 'C', 'FRANCHISE EXCEPTIONNELLE SUITE AT', 'Franchise exceptionnelle AT', ARRAY['franchise', 'exceptionnelle', 'AT'], false, false, true, false, false, true, true, true, false, false),
('C522', 'C', 'FRANCHISE CONDITIONNELLE SUITE AT', 'Franchise conditionnelle AT', ARRAY['franchise', 'conditionnelle', 'AT'], false, false, true, false, false, true, true, true, false, false),
('C531', 'C', 'FRANCHISE TOTALE SUITE AT TITRE CODE INVESTISSEMENTS', 'Investissement franchise AT', ARRAY['investissement', 'franchise', 'AT'], false, false, true, false, false, true, true, true, false, false),
('C532', 'C', 'TAXATION PARTIELLE SUITE AT TITRE CODE DES INVESTISSEMENTS', 'Investissement partiel AT', ARRAY['investissement', 'partiel', 'AT'], true, false, true, false, true, true, true, true, false, false),
('C533', 'C', 'REGIME STABILISE SUITE AT TITRE CODE DES INVESTISSEMENTS', 'Stabilisé AT', ARRAY['stabilisé', 'AT'], true, false, true, false, true, true, true, true, false, false),
('C534', 'C', 'EXONERATION PARTIELLE TVA SUITE AT', 'Exonération TVA AT', ARRAY['TVA', 'exonération', 'AT'], true, true, true, true, false, true, true, true, true, true),
('C538', 'C', 'DROIT SUSPENDU', 'Droit suspendu AT', ARRAY['suspension', 'AT'], false, false, false, false, false, false, false, false, false, false),
('C539', 'C', 'MAC NOUVEAU CODE INVESTISSEMENT SUITE AT', 'Nouveau code investissement AT', ARRAY['nouveau code', 'investissement', 'AT'], false, false, true, false, false, true, true, true, false, false),
('C540', 'C', 'FRANCHISE DIPLOMATIQUE SUITE AT', 'Diplomatique AT', ARRAY['diplomatique', 'AT'], false, false, false, false, false, false, false, false, false, false),
('C590', 'C', 'LIQUIDATION SUPPLEMENTAIRE', 'Liquidation AT', ARRAY['liquidation', 'AT'], true, true, true, true, true, true, true, true, true, true),

-- C6XX - Suite importation temporaire
('C600', 'C', 'MISE A LA CONSOMMATION SUITE D''IMPORTATION TEMPORAIRE', 'Importation temporaire', ARRAY['importation temporaire', 'IT', 'temporaire'], true, true, true, true, true, true, true, true, true, true),
('C611', 'C', 'DONS ET AIDES SUITE IMPORTATION DIRECTE DESTINES A L''ETAT', 'Dons État IT', ARRAY['dons', 'état', 'IT'], false, false, false, false, false, false, false, false, false, false),
('C612', 'C', 'DESTINES A LA CROIX-ROUGE ET AUX OEUVRES DE BIENFAISANCE', 'Dons Croix-Rouge IT', ARRAY['croix-rouge', 'bienfaisance', 'IT'], false, false, false, false, false, false, false, false, false, false),
('C613', 'C', 'A CARACTERE CULTUREL ET SOCIAL', 'Dons social IT', ARRAY['social', 'culturel', 'IT'], false, false, false, false, false, false, false, false, false, false),
('C621', 'C', 'EXEMPTION EXCEPTIONNELLE SUITE IMPORTATION TEMPORAIRE', 'Exemption exceptionnelle IT', ARRAY['exemption', 'exceptionnelle', 'IT'], false, false, true, false, false, true, true, true, false, false),
('C622', 'C', 'FRANCHISE CONDITIONNELLE SUITE IMPORTATION TEMPORAIRE', 'Franchise conditionnelle IT', ARRAY['franchise', 'conditionnelle', 'IT'], false, false, true, false, false, true, true, true, false, false),
('C631', 'C', 'MISE A CONSOMMATION SUITE IT AU TITRE DU CODE INVESTISSEMENT', 'Investissement IT', ARRAY['investissement', 'IT'], false, false, true, false, false, true, true, true, false, false),
('C634', 'C', 'EXONERATION PARTIELLE TVA SUITE IT', 'Exonération TVA IT', ARRAY['TVA', 'exonération', 'IT'], true, true, true, true, false, true, true, true, true, true),
('C639', 'C', 'MAC SUITE IMPORTATION TEMPORAIRE NVEAU CODE INVESTISSEMENT', 'Nouveau code investissement IT', ARRAY['nouveau code', 'investissement', 'IT'], false, false, true, false, false, true, true, true, false, false),
('C640', 'C', 'MISE CONSOM SUITE IMPORT.TEMPORAIRE.FRANCHISE.DIPLOMATIQUE', 'Diplomatique IT', ARRAY['diplomatique', 'IT'], false, false, false, false, false, false, false, false, false, false),
('C690', 'C', 'LIQUIDATION SUPPLEMENTAIRE', 'Liquidation IT', ARRAY['liquidation', 'IT'], true, true, true, true, true, true, true, true, true, true),

-- C7XX - Suite ZES
('C700', 'C', 'MISE A LA CONSOMMATION SUITE ZES (TAXATION NORMALE)', 'ZES taxation normale', ARRAY['ZES', 'zone économique', 'spéciale'], true, true, true, true, true, true, true, true, true, true),
('C711', 'C', 'MISE A LA CONSOMMATION SUITE ZES POUR DONS ET AIDES A L''ETAT', 'Dons État ZES', ARRAY['dons', 'état', 'ZES'], false, false, false, false, false, false, false, false, false, false),
('C712', 'C', 'MISE A LA CONSOMMATION SUITE ZES POUR DONS CROIX ROUGE', 'Dons Croix-Rouge ZES', ARRAY['croix-rouge', 'ZES'], false, false, false, false, false, false, false, false, false, false),
('C713', 'C', 'MISE A LA CONSOMMATION SUITE ZES POUR DONS SOCIAL', 'Dons social ZES', ARRAY['social', 'ZES'], false, false, false, false, false, false, false, false, false, false),
('C721', 'C', 'MISE A LA CONSOMMATION EN FRANCHISE EXCEPTIONNELLE SUITE ZES', 'Franchise exceptionnelle ZES', ARRAY['franchise', 'exceptionnelle', 'ZES'], false, false, true, false, false, true, true, true, false, false),
('C722', 'C', 'MISE A LA CONSOMMATION SUITE ZES FRANCHISE CONDITIONNELLE', 'Franchise conditionnelle ZES', ARRAY['franchise', 'conditionnelle', 'ZES'], false, false, true, false, false, true, true, true, false, false),
('C727', 'C', 'MISE CONSOMMATION CARBURANT VEHICULES UTILITAIRES ENTREPRISES ZES', 'Carburant ZES', ARRAY['carburant', 'véhicules', 'ZES'], false, false, true, false, false, true, true, true, false, false),
('C734', 'C', 'MISE A LA CONSOMMATION SUITE ZES AVEC EXONERATION DE LA TVA', 'Exonération TVA ZES', ARRAY['TVA', 'exonération', 'ZES'], true, true, true, true, false, true, true, true, true, true),
('C736', 'C', 'MISE A LA CONSOMMATION SUITE ZES AVEC EXONERATION TOTALE', 'Exonération totale ZES', ARRAY['exonération', 'totale', 'ZES'], false, false, false, false, false, false, false, false, false, false),
('C738', 'C', 'MISE CONSOMMATION SUITE ZES SUSPENSION PROVISOIRE DROITS TAXES', 'Suspension ZES', ARRAY['suspension', 'ZES'], false, false, false, false, false, false, false, false, false, false),
('C739', 'C', 'MISE CONSOMMATION SUITE ZES NOUVEAU CODE INVESTISSEMENTS', 'Nouveau code investissement ZES', ARRAY['nouveau code', 'investissement', 'ZES'], false, false, true, false, false, true, true, true, false, false),
('C740', 'C', 'MISE A LA CONSOMMATION SUITE ZES POUR PRIVILEGES DIPLOMATIQUES', 'Diplomatique ZES', ARRAY['diplomatique', 'ZES'], false, false, false, false, false, false, false, false, false, false),
('C790', 'C', 'MISE A LA CONSOMMATION SUITE ZES DE VEHICULES (TAXATION NORMALE)', 'Véhicules ZES', ARRAY['véhicules', 'ZES'], true, true, true, true, true, true, true, true, true, true),

-- C8XX - Suite exportation temporaire
('C800', 'C', 'MISE A LA CONSOMMATION EN SUITE D''EXPORTATION TEMPORAIRE', 'Exportation temporaire', ARRAY['exportation temporaire', 'retour'], true, true, true, true, true, true, true, true, true, true),
('C810', 'C', 'MISE CONSOM.DONS ET AIDES SUITE EXPORTATION TEMPORAIRE', 'Dons export temporaire', ARRAY['dons', 'exportation temporaire'], false, false, false, false, false, false, false, false, false, false),
('C821', 'C', 'FRANCHISE EXCEPTIONNELLE SUITE EXPORT.TEMPORAIRE', 'Franchise exceptionnelle export temp', ARRAY['franchise', 'exceptionnelle', 'exportation temporaire'], false, false, true, false, false, true, true, true, false, false),
('C822', 'C', 'FRANCHISE CONDITIONNELLE SUITE EXPORT.TEMPORAIRE', 'Franchise conditionnelle export temp', ARRAY['franchise', 'conditionnelle', 'exportation temporaire'], false, false, true, false, false, true, true, true, false, false),
('C831', 'C', 'MISE CONSOM.SUITE EXPORT.TEMPO.TITRE CODE INVESTISSEMENTS', 'Investissement export temp', ARRAY['investissement', 'exportation temporaire'], false, false, true, false, false, true, true, true, false, false),
('C832', 'C', 'TAXATION PARTIELLE SUITE EXPORT.TEMPO.TITRE CODE INVESTIS.', 'Investissement partiel export temp', ARRAY['investissement', 'partiel', 'exportation temporaire'], true, false, true, false, true, true, true, true, false, false),
('C833', 'C', 'REGIME STABILISE SUITE EXPORT.TEMPO.TITRE CODE INVESTIS.', 'Stabilisé export temp', ARRAY['stabilisé', 'exportation temporaire'], true, false, true, false, true, true, true, true, false, false),
('C834', 'C', 'EXONERATION PARTIELLE TVA SUITE EXPORTATION TEMPORAIRE', 'Exonération TVA export temp', ARRAY['TVA', 'exonération', 'exportation temporaire'], true, true, true, true, false, true, true, true, true, true),
('C838', 'C', 'DROIT SUSPENDU', 'Droit suspendu export temp', ARRAY['suspension', 'exportation temporaire'], false, false, false, false, false, false, false, false, false, false),
('C840', 'C', 'MISE CONSOMM.SUITE EXPORTATION TEMPORAIRE.FRANCHISE.DIPLO.', 'Diplomatique export temp', ARRAY['diplomatique', 'exportation temporaire'], false, false, false, false, false, false, false, false, false, false),
('C890', 'C', 'LIQUIDATION SUPPLEMENTAIRE', 'Liquidation export temp', ARRAY['liquidation', 'exportation temporaire'], true, true, true, true, true, true, true, true, true, true),

-- C9XX - Sortie zone franche
('C930', 'C', 'SORTIE DE ZONE FRANCHE', 'Sortie zone franche', ARRAY['zone franche', 'sortie', 'ZFID'], true, true, true, true, true, true, true, true, true, true),
('C931', 'C', 'MISE CONSOMMATION EN SORTIE DE ZFID (TAXATION NORMALE)', 'ZFID taxation normale', ARRAY['ZFID', 'zone franche', 'taxation'], true, true, true, true, true, true, true, true, true, true),
('C932', 'C', 'MISE CONSOMMATION SUITE A LA ZFID (FRANCHISE TOTALE)', 'ZFID franchise totale', ARRAY['ZFID', 'franchise', 'totale'], false, false, false, false, false, false, false, false, false, false),
('C933', 'C', 'MISE CONSOMMATION SUITE ZFID (REGIMES STABILISES)', 'ZFID stabilisé', ARRAY['ZFID', 'stabilisé'], true, false, true, false, true, true, true, true, false, false),
('C934', 'C', 'MISE CONSOM.SUITE ZFID (FRANCHISE AU TITRE DU CODE INVEST.)', 'ZFID investissement', ARRAY['ZFID', 'investissement'], false, false, true, false, false, true, true, true, false, false),
('C935', 'C', 'MISE CONSOM.SUITE ZFID (TAXATION PARTIELLE TITRE C.INVEST.)', 'ZFID investissement partiel', ARRAY['ZFID', 'investissement', 'partiel'], true, false, true, false, true, true, true, true, false, false),
('C938', 'C', 'DROIT SUSPENDU SUITE ZFI', 'Droit suspendu ZFID', ARRAY['suspension', 'ZFID'], false, false, false, false, false, false, false, false, false, false),
('C939', 'C', 'MISE A LA CONSOMMATION DE VEHICULES ET MATERIELS APRES ZFI', 'Véhicules ZFID', ARRAY['véhicules', 'ZFID'], true, true, true, true, true, true, true, true, true, true),
('C950', 'C', 'CONSOMMATION SUITE ENTREP.FRANCH.PRIVILEGE DIPLOMATIQUE', 'Diplomatique entreprise franche', ARRAY['diplomatique', 'entreprise franche'], false, false, false, false, false, false, false, false, false, false),
('C951', 'C', 'CONSOMMATION EN SORTIE D''ENTREP.FRANCHE.TAXATION NORMALE', 'Entreprise franche taxation normale', ARRAY['entreprise franche', 'taxation'], true, true, true, true, true, true, true, true, true, true),
('C952', 'C', 'CONSOMMATION EN SORTIE ENTREP.FRANCH.EXONERATION TOTALE', 'Entreprise franche exonération', ARRAY['entreprise franche', 'exonération'], false, false, false, false, false, false, false, false, false, false),
('C953', 'C', 'CONSOMMATION CARBURANT PAR ENTREPRISE FRANCHE EXPORTATION', 'Carburant entreprise franche', ARRAY['carburant', 'entreprise franche'], false, false, true, false, false, true, true, true, false, false),
('C954', 'C', 'CONSOMMATION EN SORTIE ENTREP.FRANCH.EXO CODE INVESTISSEMNT', 'Investissement entreprise franche', ARRAY['investissement', 'entreprise franche'], false, false, true, false, false, true, true, true, false, false),
('C955', 'C', 'CONSOMMATION SUITE ENTREP.FRANCH.TAXATION PARTIELLE CI', 'Entreprise franche partiel', ARRAY['entreprise franche', 'partiel'], true, false, true, false, true, true, true, true, false, false),
('C958', 'C', 'CONSOMMATION SUITE ENTREP.FRANCH.SUSPENSION PROVISOIRE', 'Suspension entreprise franche', ARRAY['suspension', 'entreprise franche'], false, false, false, false, false, false, false, false, false, false),
('C970', 'C', 'Mise a la consommation suite EFE Privilege diplomatique', 'Diplomatique EFE', ARRAY['diplomatique', 'EFE'], false, false, false, false, false, false, false, false, false, false),
('C971', 'C', 'Mise a la consommation en sortie d EFE Taxation normale', 'EFE taxation normale', ARRAY['EFE', 'taxation'], true, true, true, true, true, true, true, true, true, true),
('C972', 'C', 'Mise a la consommation en sortie d EFE Exoneration totale', 'EFE exonération totale', ARRAY['EFE', 'exonération'], false, false, false, false, false, false, false, false, false, false),
('C973', 'C', 'Entree ou consommation de carburant en EFE', 'Carburant EFE', ARRAY['carburant', 'EFE'], false, false, true, false, false, true, true, true, false, false),
('C974', 'C', 'Mise a la consommation en sortie d EFE Exoneration Code Invest', 'Investissement EFE', ARRAY['investissement', 'EFE'], false, false, true, false, false, true, true, true, false, false),
('C978', 'C', 'Mise a la consommation suite EFE suspension provisoire', 'Suspension EFE', ARRAY['suspension', 'EFE'], false, false, false, false, false, false, false, false, false, false),
('C990', 'C', 'LIQUIDATION SUPPLEMENTAIRE', 'Liquidation zone franche', ARRAY['liquidation', 'zone franche'], true, true, true, true, true, true, true, true, true, true);