-- S - Régimes suspensifs (Transit, Entrepôt, AT, IT, ZES, ZFID, EFE)
INSERT INTO public.customs_regimes (code, category, name, use_case, keywords, dd, stx, rs, tin, tva, cosec, pcs, pcc, tpast, ta) VALUES
-- S0XX - RILA
('S010', 'S', 'ENTREE EN RILA SUITE IMPORTATION DIRECTE', 'Régime industriel libératoire anticipé', ARRAY['RILA', 'industriel', 'anticipé'], false, false, false, false, false, false, false, false, false, false),
('S011', 'S', 'ENTREE EN RILA SUITE ENTREPOT DE STOCKAGE', 'RILA suite entrepôt', ARRAY['RILA', 'entrepôt'], false, false, false, false, false, false, false, false, false, false),
('S012', 'S', 'ENTREE EN RILA SUITE ENTREPOT INDUSTRIEL', 'RILA suite entrepôt industriel', ARRAY['RILA', 'entrepôt', 'industriel'], false, false, false, false, false, false, false, false, false, false),
('S013', 'S', 'ENTREE EN RILA SUITE ENTREPOT APRES AT SPECIALE', 'RILA suite AT', ARRAY['RILA', 'AT', 'spéciale'], false, false, false, false, false, false, false, false, false, false),
('S014', 'S', 'ENTREE EN RILA SUITE AT EXCEPTIONNELLE', 'RILA suite AT exceptionnelle', ARRAY['RILA', 'AT', 'exceptionnelle'], false, false, false, false, false, false, false, false, false, false),
('S015', 'S', 'ENTREE EN RILA DE MARCHANDISES PRISES SUR LE MARCHE LOCAL', 'RILA marché local', ARRAY['RILA', 'marché local'], false, false, false, false, false, false, false, false, false, false),
('S016', 'S', 'ENTREE EN RILA SUITE AT POUR PERFECTIONNEMENT ACTIF', 'RILA perfectionnement actif', ARRAY['RILA', 'perfectionnement actif'], false, false, false, false, false, false, false, false, false, false),
('S017', 'S', 'ENTREE EN RILA SUITE ZES', 'RILA suite ZES', ARRAY['RILA', 'ZES'], false, false, false, false, false, false, false, false, false, false),
('S018', 'S', 'ENTREE EN RILA SUITE SUSPENSION PROVISOIRE', 'RILA suspension', ARRAY['RILA', 'suspension'], false, false, false, false, false, false, false, false, false, false),
('S019', 'S', 'ENTREE EN RILA SUITE EFE', 'RILA suite EFE', ARRAY['RILA', 'EFE'], false, false, false, false, false, false, false, false, false, false),

-- S1XX - Transit PNP
('S110', 'S', 'TRANSIT ORDINAIRE SUITE IMPORTATION DIRECTE', 'Transit vers pays tiers (Mali, Burkina, etc.)', ARRAY['transit', 'passage', 'Mali', 'Burkina', 'corridor', 'tiers'], false, false, false, false, false, false, false, false, false, false),
('S111', 'S', 'TRANSIT ORDINAIRE SUITE REGIME SUSPENSIF', 'Transit suite régime suspensif', ARRAY['transit', 'suspensif'], false, false, false, false, false, false, false, false, false, false),
('S120', 'S', 'TRANSIT INTERNATIONAL (TRIE)', 'Transit international routier interétatique', ARRAY['TRIE', 'international', 'routier', 'interétatique', 'transit'], false, false, false, false, false, false, false, false, false, false),
('S121', 'S', 'TRANSIT INTERNAT. DE PNP EN SUITE D''ENTREPOT', 'TRIE suite entrepôt', ARRAY['TRIE', 'entrepôt'], false, false, false, false, false, false, false, false, false, false),

-- S2XX - Transit PP
('S210', 'S', 'TRANSIT ORDINAIRE SUITE IMPORT. DIRECTE PROD. PETROL.', 'Transit produits pétroliers', ARRAY['transit', 'PP', 'pétrolier'], false, false, false, false, false, false, false, false, false, false),
('S211', 'S', 'TRANSIT ORDINAIRE EN SUITE D''ENTREPOT', 'Transit entrepôt PP', ARRAY['transit', 'entrepôt', 'PP'], false, false, false, false, false, false, false, false, false, false),
('S220', 'S', 'TRANSIT INTERNATIONAL DE PRODUITS PETROLIERS', 'TRIE PP', ARRAY['TRIE', 'PP', 'pétrolier'], false, false, false, false, false, false, false, false, false, false),
('S221', 'S', 'TRANSIT INTERNATIONAL DE PRDS PETROLIERS SUITE REG.SUSPENSIF', 'TRIE PP suspensif', ARRAY['TRIE', 'PP', 'suspensif'], false, false, false, false, false, false, false, false, false, false),

-- S3XX - Entrepôt PNP
('S300', 'S', 'ENTREE EN ENTREPOT FICTIF PRIVE SUITE TRANSB.DEPOT,TRANSIT', 'Entrepôt privé', ARRAY['entrepôt', 'privé', 'stockage', 'suspensif'], false, false, false, false, false, false, false, false, false, false),
('S301', 'S', 'ENTREE EN ENTREPOT FICTIF PRIVE SUITE D''ENTREPOT (MUTATION)', 'Mutation entrepôt privé', ARRAY['entrepôt', 'privé', 'mutation'], false, false, false, false, false, false, false, false, false, false),
('S302', 'S', 'ENTREPOT PRIVE APRES AT POUR OUVRAISON DE PNP', 'Entrepôt suite AT', ARRAY['entrepôt', 'privé', 'AT', 'ouvraison'], false, false, false, false, false, false, false, false, false, false),
('S303', 'S', 'ENTREPOT PRIVE SUITE AUTRES CATEGORIES D''ENTREPOT', 'Entrepôt autre catégorie', ARRAY['entrepôt', 'privé'], false, false, false, false, false, false, false, false, false, false),
('S310', 'S', 'ENTREPOT PUBLIC SUITE IMPORTATION DIRECTE', 'Entrepôt public', ARRAY['entrepôt', 'public', 'MTTA'], false, false, false, false, false, false, false, false, false, false),
('S311', 'S', 'MUTATION ENTREPOTS PUB.ENTR.PUB.SUITE ENTREP.PUBLIC', 'Mutation entrepôt public', ARRAY['entrepôt', 'public', 'mutation'], false, false, false, false, false, false, false, false, false, false),
('S312', 'S', 'ENTREPOT PUBLIC SUITE ADMISSION TEMPORAIRE', 'Entrepôt public AT', ARRAY['entrepôt', 'public', 'AT'], false, false, false, false, false, false, false, false, false, false),
('S320', 'S', 'ENTREE EN ENTREP.INDUSTRIEL SUITE IMPORTATION DIRECTE', 'Entrepôt industriel', ARRAY['entrepôt', 'industriel', 'transformation'], false, false, false, false, false, false, false, false, false, false),
('S321', 'S', 'ENTREE EN ENTREP.INDUSTRIEL SUITE D''ENTREPOT (MUTATION)', 'Mutation entrepôt industriel', ARRAY['entrepôt', 'industriel', 'mutation'], false, false, false, false, false, false, false, false, false, false),
('S322', 'S', 'ENTREE EN ENTREP.INDUSTRIEL SUITE REGIMES D''OUVRAISON', 'Entrepôt industriel ouvraison', ARRAY['entrepôt', 'industriel', 'ouvraison'], false, false, false, false, false, false, false, false, false, false),

-- S4XX - Entrepôt PP
('S400', 'S', 'ENTREE EN ENTREPOT FICTIF PRIVE SUITE TRANSB.DEPOT,TRANSIT PP', 'Entrepôt privé PP', ARRAY['entrepôt', 'privé', 'PP'], false, false, false, false, false, false, false, false, false, false),
('S401', 'S', 'ENTREE EN ENTREPOT FICTIF PRIVE SUITE D''ENTREPOT PP', 'Mutation entrepôt PP', ARRAY['entrepôt', 'privé', 'mutation', 'PP'], false, false, false, false, false, false, false, false, false, false),
('S402', 'S', 'ENTREE EN ENTREPOT PRIVE APRES AT DE PP', 'Entrepôt suite AT PP', ARRAY['entrepôt', 'privé', 'AT', 'PP'], false, false, false, false, false, false, false, false, false, false),
('S403', 'S', 'ENTREE EN ENTREPOT FICTIF PRIVE SUITE AT OUVRAISON', 'Entrepôt AT ouvraison PP', ARRAY['entrepôt', 'privé', 'AT', 'ouvraison', 'PP'], false, false, false, false, false, false, false, false, false, false),
('S404', 'S', 'ENTREE EN CONSIGNATION DE PRODUITS PETROLIERS', 'Consignation PP', ARRAY['consignation', 'PP', 'pétrolier'], false, false, false, false, false, false, false, false, false, false),
('S405', 'S', 'ENTREE DE PRODUITS PETROLIERS EN SOUTES NATIONALES', 'Soutes nationales', ARRAY['soutes', 'nationales', 'PP'], false, false, false, false, false, false, false, false, false, false),
('S410', 'S', 'CESSION DE PRODUITS PETROLIERS SUITE CONSIGNATION', 'Cession consignation PP', ARRAY['cession', 'consignation', 'PP'], false, false, false, false, false, false, false, false, false, false),
('S414', 'S', 'MUTATIONS EN SUITE DE SOUTES INTERNATIONALES DE PP', 'Mutation soutes internationales', ARRAY['mutation', 'soutes', 'internationales', 'PP'], false, false, false, false, false, false, false, false, false, false),
('S415', 'S', 'MUTATION DE PRODUITS PETROLIERS EN SOUTES NATIONALES', 'Mutation soutes nationales', ARRAY['mutation', 'soutes', 'nationales', 'PP'], false, false, false, false, false, false, false, false, false, false),
('S420', 'S', 'ENTREE EN ENTREPOT INDUSTRIEL SUITE IMPORT DIRECTE PP', 'Entrepôt industriel PP', ARRAY['entrepôt', 'industriel', 'PP'], false, false, false, false, false, false, false, false, false, false),
('S421', 'S', 'ENTREE EN ENTREPOT INDUSTRIEL SUITE D''ENTREPOT PP', 'Mutation entrepôt industriel PP', ARRAY['entrepôt', 'industriel', 'mutation', 'PP'], false, false, false, false, false, false, false, false, false, false),
('S422', 'S', 'ENTREE EN ENTREPOT INDUSTRIEL SUITE D''AT PP', 'Entrepôt industriel AT PP', ARRAY['entrepôt', 'industriel', 'AT', 'PP'], false, false, false, false, false, false, false, false, false, false),
('S450', 'S', 'ENTREE EN USINE EXERCEE DE PP (REGIME SAR)', 'Usine exercée SAR', ARRAY['usine', 'SAR', 'PP', 'raffinerie'], false, false, false, false, false, false, false, false, false, false),
('S451', 'S', 'BORDEREAU LIVRAISON PRDTS PETROLIERS POUR MARCHE LOCAL', 'Bordereau PP marché local', ARRAY['bordereau', 'PP', 'marché local'], false, false, false, false, false, false, false, false, false, false),
('S452', 'S', 'BORDEREAU LIVRAISON PRDTS PETROLIERS DESTINES REEXPORTATION', 'Bordereau PP réexportation', ARRAY['bordereau', 'PP', 'réexportation'], false, false, false, false, false, false, false, false, false, false),

-- S5XX - Admission Temporaire
('S500', 'S', 'ENTREE EN ATS POUR RILA SUITE IMPORTATION DIRECTE', 'ATS pour RILA', ARRAY['ATS', 'RILA', 'AT'], false, false, false, false, false, false, false, false, false, false),
('S501', 'S', 'ENTREE EN ATS SUITE RILA', 'ATS suite RILA', ARRAY['ATS', 'RILA'], false, false, false, false, false, false, false, false, false, false),
('S510', 'S', 'ENTREE EN AT SPECIALE SUITE IMPORTATION DIRECTE', 'AT spéciale', ARRAY['AT', 'spéciale', 'ouvraison', 'transformation'], false, false, false, false, false, false, false, false, false, false),
('S511', 'S', 'ENTREE EN ATS SUITE ENTREPOT', 'ATS suite entrepôt', ARRAY['ATS', 'entrepôt'], false, false, false, false, false, false, false, false, false, false),
('S520', 'S', 'ENTREE EN AT EXCEPTIONNELLE SUITE IMPORTATION DIRECTE', 'AT exceptionnelle', ARRAY['AT', 'exceptionnelle', 'matériel', 'équipement', 'chantier'], false, false, false, false, false, false, false, false, false, false),
('S521', 'S', 'ENTREE EN AT EXCEPTIONNELLE SUITE ENTREPOT', 'AT exceptionnelle entrepôt', ARRAY['AT', 'exceptionnelle', 'entrepôt'], false, false, false, false, false, false, false, false, false, false),
('S530', 'S', 'ENTREE EN AT POUR PERFECTIONNEMENT ACTIF SUITE IMPORT DIRECT', 'Perfectionnement actif', ARRAY['perfectionnement actif', 'AT', 'transformation', 'export'], false, false, false, false, false, false, false, false, false, false),
('S531', 'S', 'ENTREE EN AT PERFECTIONNEMENT ACTIF SUITE ENTREPOT', 'Perfectionnement actif entrepôt', ARRAY['perfectionnement actif', 'AT', 'entrepôt'], false, false, false, false, false, false, false, false, false, false),
('S535', 'S', 'CESSION D''EMBALLAGES SOUS AT A EXPORTATEURS PRDTS SENEGALAIS', 'Cession emballages AT', ARRAY['emballages', 'AT', 'cession', 'exportateurs'], false, false, false, false, false, false, false, false, false, false),
('S550', 'S', 'MUTATION DIRECTE D''AT A AT D''EMBALLAGES', 'Mutation AT emballages', ARRAY['mutation', 'AT', 'emballages'], false, false, false, false, false, false, false, false, false, false),
('S551', 'S', 'ENTREE EN AT SUITE EFE', 'AT suite EFE', ARRAY['AT', 'EFE'], false, false, false, false, false, false, false, false, false, false),

-- S6XX - Importation Temporaire
('S600', 'S', 'IMPORTATION TEMPORAIRE SUITE IMPORTATION DIRECTE', 'Importation temporaire', ARRAY['importation temporaire', 'IT', 'exposition', 'foire', 'salon', 'temporaire'], false, false, false, false, false, false, false, false, false, false),
('S601', 'S', 'ENTREE EN IT SUITE REGIME SUSPENSIF', 'IT suite suspensif', ARRAY['IT', 'suspensif'], false, false, false, false, false, false, false, false, false, false),
('S602', 'S', 'MUTATION D''IMPORTATION TEMPORAIRE', 'Mutation IT', ARRAY['IT', 'mutation'], false, false, false, false, false, false, false, false, false, false),

-- S7XX - ZES
('S700', 'S', 'ENTREE EN ZES SUITE IMPORTATION DIRECTE', 'Zone économique spéciale', ARRAY['ZES', 'zone économique', 'spéciale', 'Diamniadio'], false, false, false, false, false, false, false, false, false, false),
('S705', 'S', 'ENTREE EN ZES DE MARCHANDISES PRISES SUR LE MARCHE LOCAL', 'ZES marché local', ARRAY['ZES', 'marché local'], false, false, false, false, false, false, false, false, false, false),
('S731', 'S', 'ENTREE EN ZES SUITE ENTREPOT', 'ZES suite entrepôt', ARRAY['ZES', 'entrepôt'], false, false, false, false, false, false, false, false, false, false),
('S732', 'S', 'ENTREE EN ZES SUITE ENTREPOT INDUSTRIEL', 'ZES suite entrepôt industriel', ARRAY['ZES', 'entrepôt', 'industriel'], false, false, false, false, false, false, false, false, false, false),
('S735', 'S', 'ENTREE EN ZES SUITE ENTREPOT APRES AT', 'ZES suite AT', ARRAY['ZES', 'AT'], false, false, false, false, false, false, false, false, false, false),
('S751', 'S', 'ENTREE EN ZES SUITE AT EXCEPTIONNELLE', 'ZES AT exceptionnelle', ARRAY['ZES', 'AT', 'exceptionnelle'], false, false, false, false, false, false, false, false, false, false),
('S752', 'S', 'ENTREE EN ZES SUITE AT POUR PERFECTIONNEMENT ACTIF', 'ZES perfectionnement actif', ARRAY['ZES', 'perfectionnement actif'], false, false, false, false, false, false, false, false, false, false),
('S753', 'S', 'ENTREE EN ZES SUITE AT SPECIALE', 'ZES AT spéciale', ARRAY['ZES', 'AT', 'spéciale'], false, false, false, false, false, false, false, false, false, false),
('S754', 'S', 'ENTREE EN ZES SUITE AT EXCEPTIONNELLE POUR PERFECTIONNEMENT', 'ZES AT perfectionnement', ARRAY['ZES', 'AT', 'perfectionnement'], false, false, false, false, false, false, false, false, false, false),
('S771', 'S', 'CESSION DE MARCHANDISES ENTRE ENTREPRISES ZES', 'Cession ZES', ARRAY['ZES', 'cession', 'entreprises'], false, false, false, false, false, false, false, false, false, false),
('S781', 'S', 'ENTREE EN ZES DE PRODUITS PREALABLEMENT REEXPORTES', 'ZES retour réexportation', ARRAY['ZES', 'retour', 'réexportation'], false, false, false, false, false, false, false, false, false, false),
('S790', 'S', 'ENTREE EN ZES DE VEHICULES SUITE IMPORTATION DIRECTE', 'ZES véhicules', ARRAY['ZES', 'véhicules'], false, false, false, false, false, false, false, false, false, false),
('S791', 'S', 'ENTREE EN ZES DE VEHICULES SUITE REGIME SUSPENSIF', 'ZES véhicules suspensif', ARRAY['ZES', 'véhicules', 'suspensif'], false, false, false, false, false, false, false, false, false, false),

-- S9XX - Zone Franche et EFE
('S930', 'S', 'ENTREE EN ZONE FRANCHE INDUSTRIELLE', 'Zone franche industrielle', ARRAY['zone franche', 'ZFID', 'industrielle'], false, false, false, false, false, false, false, false, false, false),
('S931', 'S', 'ENTREE EN ZFID SUITE D''IMPORTATION DIRECTE', 'ZFID import direct', ARRAY['ZFID', 'importation'], false, false, false, false, false, false, false, false, false, false),
('S932', 'S', 'ENTREE EN ZFID SUITE ENTREPOT', 'ZFID entrepôt', ARRAY['ZFID', 'entrepôt'], false, false, false, false, false, false, false, false, false, false),
('S933', 'S', 'ENTREE ZFID SUITE ENTREPOT APRES AT', 'ZFID AT', ARRAY['ZFID', 'AT'], false, false, false, false, false, false, false, false, false, false),
('S934', 'S', 'ENTREE EN ZFID SUITE REGIMES D''OUVRAISON', 'ZFID ouvraison', ARRAY['ZFID', 'ouvraison'], false, false, false, false, false, false, false, false, false, false),
('S935', 'S', 'ENTREE EN ZFID MARCHANDISES PRELEVEES SUR LE MARCHE LOCAL', 'ZFID marché local', ARRAY['ZFID', 'marché local'], false, false, false, false, false, false, false, false, false, false),
('S938', 'S', 'ENTREE EN ZFID DE VEHICULES ET MATERIELS SUITE REG.SUSP', 'ZFID véhicules suspensif', ARRAY['ZFID', 'véhicules', 'suspensif'], false, false, false, false, false, false, false, false, false, false),
('S939', 'S', 'ENTREE EN ZFID DE VEHICULES ET MATERIELS SUITE IMP.DIRECT', 'ZFID véhicules direct', ARRAY['ZFID', 'véhicules'], false, false, false, false, false, false, false, false, false, false),
('S950', 'S', 'RETOUR EN ENTREP.FRANCH.DE PDRTS PREALABLMT.REEXPORTES', 'Retour entreprise franche', ARRAY['entreprise franche', 'retour'], false, false, false, false, false, false, false, false, false, false),
('S951', 'S', 'ENTREE EN ENTREPRISE FRANCHE SUITE IMPORTATION DIRECTE', 'Entreprise franche', ARRAY['entreprise franche', 'EFE', 'exportation'], false, false, false, false, false, false, false, false, false, false),
('S952', 'S', 'ENTREE EN ENTREPRISE FRANCHE SUITE ENTREPOT', 'Entreprise franche entrepôt', ARRAY['entreprise franche', 'entrepôt'], false, false, false, false, false, false, false, false, false, false),
('S953', 'S', 'ENTREE EN ENTREPRISE FRANCHE SUITE ENTREPOT APRES AT', 'Entreprise franche AT', ARRAY['entreprise franche', 'AT'], false, false, false, false, false, false, false, false, false, false),
('S954', 'S', 'ENTREE EN ENTREPRISE FRANCHE SUITE REGIMES D''OUVRAISON', 'Entreprise franche ouvraison', ARRAY['entreprise franche', 'ouvraison'], false, false, false, false, false, false, false, false, false, false),
('S955', 'S', 'Entrée en EFE de produits d''origine communautaire', 'EFE origine communautaire', ARRAY['EFE', 'communautaire', 'UEMOA'], false, false, false, false, false, false, false, false, false, false),
('S956', 'S', 'Entrée en EFE de produits nationalisés suite paiement droits', 'EFE nationalisés', ARRAY['EFE', 'nationalisés'], false, false, false, false, false, false, false, false, false, false),
('S958', 'S', 'ENTREPR.FRANCH.VEHICULES,MATERIELS SUITE REGIME SUSPENSIF', 'Entreprise franche véhicules suspensif', ARRAY['entreprise franche', 'véhicules', 'suspensif'], false, false, false, false, false, false, false, false, false, false),
('S959', 'S', 'ENTREPR.FRANCH.VEHICULES,MATERIELS IMPORT.DIRECT.', 'Entreprise franche véhicules direct', ARRAY['entreprise franche', 'véhicules'], false, false, false, false, false, false, false, false, false, false),
('S970', 'S', 'Retour en EFE de produits prealablement reexportes', 'Retour EFE', ARRAY['EFE', 'retour'], false, false, false, false, false, false, false, false, false, false),
('S971', 'S', 'Entree en EFE suite importation directe', 'EFE import direct', ARRAY['EFE', 'importation'], false, false, false, false, false, false, false, false, false, false),
('S972', 'S', 'Entree en EFE suite S951 ou S971', 'EFE mutation', ARRAY['EFE', 'mutation'], false, false, false, false, false, false, false, false, false, false),
('S973', 'S', 'Entree en EFE suite entrepot apres AT', 'EFE AT', ARRAY['EFE', 'AT'], false, false, false, false, false, false, false, false, false, false),
('S974', 'S', 'Entree en EFE suite regimes d''ouvraison', 'EFE ouvraison', ARRAY['EFE', 'ouvraison'], false, false, false, false, false, false, false, false, false, false),
('S975', 'S', 'Entree en EFE de produits pris sur le marche local', 'EFE marché local', ARRAY['EFE', 'marché local'], false, false, false, false, false, false, false, false, false, false),
('S978', 'S', 'Entree en EFE de vehicules suite regime suspensif', 'EFE véhicules suspensif', ARRAY['EFE', 'véhicules', 'suspensif'], false, false, false, false, false, false, false, false, false, false),
('S979', 'S', 'Entree en EFE de vehicules suite importation directe', 'EFE véhicules', ARRAY['EFE', 'véhicules'], false, false, false, false, false, false, false, false, false, false);

-- R - Réexportation
INSERT INTO public.customs_regimes (code, category, name, use_case, keywords, dd, stx, rs, tin, tva, cosec, pcs, pcc, tpast, ta) VALUES
('R100', 'R', 'REEXPORTATION EN SUITE DE DEPOT', 'Réexportation de marchandises non dédouanées', ARRAY['réexportation', 'dépôt', 'retour'], false, false, false, false, false, false, false, false, false, false),
('R110', 'R', 'REEXPORTATION DIRECTE OU EN SUITE DE TRANSIT', 'Réexportation directe', ARRAY['réexportation', 'directe', 'transit'], false, false, false, false, false, false, false, false, false, false),
('R120', 'R', 'REEXPORTATION EN SUITE DE TRANSIT', 'Réexportation transit', ARRAY['réexportation', 'transit'], false, false, false, false, false, false, false, false, false, false),
('R180', 'R', 'AVITAILLEMENT SUITE IMPORTATION DIRECTE', 'Avitaillement', ARRAY['avitaillement', 'navires'], false, false, false, false, false, false, false, false, false, false),
('R200', 'R', 'REEXPORTATION EN SUITE DE DEPOT PP', 'Réexportation dépôt PP', ARRAY['réexportation', 'dépôt', 'PP'], false, false, false, false, false, false, false, false, false, false),
('R210', 'R', 'EN SUITE DE TRANSBORDEMENT', 'Réexportation transbordement', ARRAY['réexportation', 'transbordement'], false, false, false, false, false, false, false, false, false, false),
('R220', 'R', 'REEXPORTATION EN SUITE DE TRANSIT PP', 'Réexportation transit PP', ARRAY['réexportation', 'transit', 'PP'], false, false, false, false, false, false, false, false, false, false),
('R280', 'R', 'AVITAILLEMENT SUITE IMPORT DIRECTE PP', 'Avitaillement PP', ARRAY['avitaillement', 'PP'], false, false, false, false, false, false, false, false, false, false),
('R300', 'R', 'REEXPORTATION SUITE ENTREPOT PRIVE', 'Réexportation entrepôt privé', ARRAY['réexportation', 'entrepôt', 'privé'], false, false, false, false, false, false, false, false, false, false),
('R303', 'R', 'REEXPORTATION AGOA SUITE ENTREPOT APRES AT OUVRAISON', 'Réexportation AGOA', ARRAY['réexportation', 'AGOA', 'AT'], false, false, false, false, false, false, false, false, false, false),
('R310', 'R', 'REEXPORTATION SUITE ENTREPOT PUBLIC DE PNP', 'Réexportation entrepôt public', ARRAY['réexportation', 'entrepôt', 'public'], false, false, false, false, false, false, false, false, false, false),
('R320', 'R', 'REEXPORTATION SUITE ENTREPOT INDUSTRIEL', 'Réexportation entrepôt industriel', ARRAY['réexportation', 'entrepôt', 'industriel'], false, false, false, false, false, false, false, false, false, false),
('R323', 'R', 'EXPORTATION AGOA SUITE ENTREPOT INDUSTRIEL', 'AGOA industriel', ARRAY['AGOA', 'entrepôt', 'industriel'], false, false, false, false, false, false, false, false, false, false),
('R380', 'R', 'AVITAILLEMENT SUITE ENTREPOT', 'Avitaillement entrepôt', ARRAY['avitaillement', 'entrepôt'], false, false, false, false, false, false, false, false, false, false),
('R400', 'R', 'REEXPORTATION SUITE ENTREPOT PRIVE PP', 'Réexportation entrepôt PP', ARRAY['réexportation', 'entrepôt', 'PP'], false, false, false, false, false, false, false, false, false, false),
('R404', 'R', 'REEXPORTATION DE PRODUITS PETROLIERS SUITE CONSIGNATION', 'Réexportation consignation PP', ARRAY['réexportation', 'consignation', 'PP'], false, false, false, false, false, false, false, false, false, false),
('R420', 'R', 'REEXPORTATION SUITE ENTREPOT INDUSTRIEL PP', 'Réexportation industriel PP', ARRAY['réexportation', 'entrepôt', 'industriel', 'PP'], false, false, false, false, false, false, false, false, false, false),
('R450', 'R', 'REEXPORTATION SUITE USINE EXERCEE', 'Réexportation usine', ARRAY['réexportation', 'usine', 'PP'], false, false, false, false, false, false, false, false, false, false),
('R480', 'R', 'AVITAILLEMENT SUITE ENTREPOT PP', 'Avitaillement entrepôt PP', ARRAY['avitaillement', 'entrepôt', 'PP'], false, false, false, false, false, false, false, false, false, false),
('R484', 'R', 'AVITAILLEMENT NAVIRES ETRANGERS SUITE CONSIGNATION', 'Avitaillement navires étrangers', ARRAY['avitaillement', 'navires', 'étrangers', 'consignation'], false, false, false, false, false, false, false, false, false, false),
('R485', 'R', 'AVITAILLEMENT NAVIRES ETRANGERS SUITE SOUTES NATIONALES', 'Avitaillement soutes', ARRAY['avitaillement', 'soutes', 'nationales'], false, false, false, false, false, false, false, false, false, false),
('R500', 'R', 'EN SUITE D''ADMISSION TEMPORAIRE ORDINAIRE', 'Réexportation AT', ARRAY['réexportation', 'AT'], false, false, false, false, false, false, false, false, false, false),
('R503', 'R', 'REEXPORTATION AGOA EN SUITE D''AT OUVRAISON', 'Réexportation AGOA AT', ARRAY['réexportation', 'AGOA', 'AT'], false, false, false, false, false, false, false, false, false, false),
('R510', 'R', 'REEXPORTATION EN SUITE D''AT SPECIALE', 'Réexportation AT spéciale', ARRAY['réexportation', 'AT', 'spéciale'], false, false, false, false, false, false, false, false, false, false),
('R520', 'R', 'REEXPORTATION EN SUITE D''AT EXCEPTIONNELLE', 'Réexportation AT exceptionnelle', ARRAY['réexportation', 'AT', 'exceptionnelle'], false, false, false, false, false, false, false, false, false, false),
('R530', 'R', 'REEXPORTATION SUITE AT POUR PERFECTIONNEMENT ACTIF', 'Réexportation perfectionnement', ARRAY['réexportation', 'perfectionnement actif'], false, false, false, false, false, false, false, false, false, false),
('R531', 'R', 'REEXPORTATION SUITE ATN APRES ENTREPOT', 'Réexportation ATN', ARRAY['réexportation', 'ATN', 'entrepôt'], false, false, false, false, false, false, false, false, false, false),
('R535', 'R', 'REEXPORTATION D''EMBALLAGES APRES CESSION', 'Réexportation emballages', ARRAY['réexportation', 'emballages', 'cession'], false, false, false, false, false, false, false, false, false, false),
('R550', 'R', 'REEXPORTATION SUITE MUTATION D''AT', 'Réexportation mutation AT', ARRAY['réexportation', 'mutation', 'AT'], false, false, false, false, false, false, false, false, false, false),
('R600', 'R', 'REEXPORTATION EN SUITE D''IMPORTATION TEMPORAIRE', 'Réexportation IT', ARRAY['réexportation', 'IT'], false, false, false, false, false, false, false, false, false, false),
('R620', 'R', 'REEXPORTATION TEMPORAIRE', 'Réexportation temporaire', ARRAY['réexportation', 'temporaire'], false, false, false, false, false, false, false, false, false, false),
('R700', 'R', 'REEXPORTATION EN L''ETAT DE PRODUITS ADMIS EN ZES', 'Réexportation ZES', ARRAY['réexportation', 'ZES'], false, false, false, false, false, false, false, false, false, false),
('R730', 'R', 'REEXPORTATION DE PRODUITS FABRIQUES SUITE ZES', 'Réexportation fabriqué ZES', ARRAY['réexportation', 'ZES', 'fabriqué'], false, false, false, false, false, false, false, false, false, false),
('R750', 'R', 'REEXPORTATION SUITE ZES D''EMBALLAGES FABRIQUES EN AT', 'Réexportation emballages ZES', ARRAY['réexportation', 'ZES', 'emballages'], false, false, false, false, false, false, false, false, false, false),
('R790', 'R', 'REEXPORTATION SUITE ZES DE VEHICULES', 'Réexportation véhicules ZES', ARRAY['réexportation', 'ZES', 'véhicules'], false, false, false, false, false, false, false, false, false, false),
('R903', 'R', 'REEXPORTATION AGOA EN SUITE REGIME FRANC', 'Réexportation AGOA zone franche', ARRAY['réexportation', 'AGOA', 'zone franche'], false, false, false, false, false, false, false, false, false, false),
('R930', 'R', 'SORTIE ZONE FRANCHE DE PRODUITS NON ORIGINAIRES', 'Réexportation zone franche', ARRAY['réexportation', 'zone franche'], false, false, false, false, false, false, false, false, false, false),
('R931', 'R', 'REEXPORTATION DE PRODUITS FABRIQUES EN ZONE FRANCHE', 'Réexportation fabriqué ZFID', ARRAY['réexportation', 'ZFID', 'fabriqué'], false, false, false, false, false, false, false, false, false, false),
('R939', 'R', 'REEXPORT.EN L''ETAT DE MARCH.(VEHICULES,MATERIELS)SUITE S939', 'Réexportation véhicules ZFID', ARRAY['réexportation', 'ZFID', 'véhicules'], false, false, false, false, false, false, false, false, false, false),
('R950', 'R', 'REEXPORTATION RESERVE DE RETOUR PRDTS ADMIS EN ENTREP.FRANCH', 'Réexportation entreprise franche retour', ARRAY['réexportation', 'entreprise franche', 'retour'], false, false, false, false, false, false, false, false, false, false),
('R951', 'R', 'REEXPORT.PRODTS FABRIQ.EN ENTREP.FRACHE SANS ORIGINE SENEGAL', 'Réexportation entreprise franche fabriqué', ARRAY['réexportation', 'entreprise franche', 'fabriqué'], false, false, false, false, false, false, false, false, false, false),
('R952', 'R', 'Réexportation de produits admis en EFE suite import directe', 'Réexportation EFE', ARRAY['réexportation', 'EFE'], false, false, false, false, false, false, false, false, false, false),
('R953', 'R', 'REEXPORT.SUITE ENTREP.FRANCH.D''EMBALLAGES FABRIQUES EN AT', 'Réexportation emballages entreprise franche', ARRAY['réexportation', 'entreprise franche', 'emballages'], false, false, false, false, false, false, false, false, false, false),
('R959', 'R', 'REEXPORTATION SUITE ENTREP.FRANCH.VEHICULES,MATERIELS', 'Réexportation véhicules entreprise franche', ARRAY['réexportation', 'entreprise franche', 'véhicules'], false, false, false, false, false, false, false, false, false, false),
('R971', 'R', 'Réexportation de produits fabriques en EFE', 'Réexportation fabriqué EFE', ARRAY['réexportation', 'EFE', 'fabriqué'], false, false, false, false, false, false, false, false, false, false),
('R972', 'R', 'Réexportation de produits admis en EFE suite import directe', 'Réexportation EFE direct', ARRAY['réexportation', 'EFE', 'importation'], false, false, false, false, false, false, false, false, false, false),
('R973', 'R', 'Réexportation suite EFE d''emballages fabriques en AT', 'Réexportation emballages EFE', ARRAY['réexportation', 'EFE', 'emballages'], false, false, false, false, false, false, false, false, false, false),
('R979', 'R', 'Réexportation suite EFE (Vehicules, Materiels ...)', 'Réexportation véhicules EFE', ARRAY['réexportation', 'EFE', 'véhicules'], false, false, false, false, false, false, false, false, false, false);

-- E - Exportation
INSERT INTO public.customs_regimes (code, category, name, use_case, keywords, dd, stx, rs, tin, tva, cosec, pcs, pcc, tpast, ta) VALUES
('E100', 'E', 'EXPORTATION SIMPLE SORTIE SANS RESTITUTION', 'Export définitif de produits sénégalais', ARRAY['exportation', 'sortie', 'définitive', 'sénégalais', 'origine'], false, false, false, false, false, false, false, false, false, false),
('E101', 'E', 'EXPORTATION SIMPLE SORTIE AVEC RESTITUTION', 'Export avec restitution', ARRAY['exportation', 'restitution'], false, false, false, false, false, false, false, false, false, false),
('E102', 'E', 'EXPORTATION EN DRAWBACK', 'Exportation avec remboursement des droits sur intrants', ARRAY['drawback', 'remboursement', 'intrants', 'export'], false, false, false, false, false, false, false, false, false, false),
('E103', 'E', 'EXPORTATION AGOA EN SIMPLE SORTIE', 'Export AGOA', ARRAY['exportation', 'AGOA'], false, false, false, false, false, false, false, false, false, false),
('E133', 'E', 'EXPORTATION DE PRODUITS SENEGALAIS BENEF. D''UN REG.STABILISE', 'Export stabilisé', ARRAY['exportation', 'stabilisé'], false, false, false, false, false, false, false, false, false, false),
('E150', 'E', 'EXPORTATION MIXTE PRODTS SENEGALAIS-EMBALLAGES SS-DOUANE', 'Export mixte', ARRAY['exportation', 'mixte', 'emballages'], false, false, false, false, false, false, false, false, false, false),
('E180', 'E', 'AVITAILLEMENT SANS RESTITUTION', 'Avitaillement export', ARRAY['avitaillement', 'exportation'], false, false, false, false, false, false, false, false, false, false),
('E181', 'E', 'AVITAILLEMENT AVEC RESTITUTION', 'Avitaillement restitution', ARRAY['avitaillement', 'restitution'], false, false, false, false, false, false, false, false, false, false),
('E199', 'E', 'REEXPORTATION EMBALLAGES SS-DOUANE CONTENANT PRDTS SENEGALAI', 'Export emballages', ARRAY['exportation', 'emballages'], false, false, false, false, false, false, false, false, false, false),
('E200', 'E', 'EXPORTATION SIMPLE SORTIE SANS RESTITUTION PP', 'Export PP', ARRAY['exportation', 'PP', 'pétrolier'], false, false, false, false, false, false, false, false, false, false),
('E201', 'E', 'EXPORTATION SIMPLE SORTIE AVEC RESTITUTION PP', 'Export PP restitution', ARRAY['exportation', 'PP', 'restitution'], false, false, false, false, false, false, false, false, false, false),
('E233', 'E', 'EXPORT DE PP SENEGALAIS BENEFICIANT D''UN REG.STABILISE', 'Export PP stabilisé', ARRAY['exportation', 'PP', 'stabilisé'], false, false, false, false, false, false, false, false, false, false),
('E280', 'E', 'AVITAILLEMENT SANS RESTITUTION PP', 'Avitaillement PP', ARRAY['avitaillement', 'PP'], false, false, false, false, false, false, false, false, false, false),
('E281', 'E', 'AVITAILLEMENT AVEC RESTITUTION PP', 'Avitaillement PP restitution', ARRAY['avitaillement', 'PP', 'restitution'], false, false, false, false, false, false, false, false, false, false),
('E800', 'E', 'EXPORTATION TEMPORAIRE POUR OUVRAISON', 'Exportation temporaire ouvraison', ARRAY['exportation temporaire', 'ouvraison'], false, false, false, false, false, false, false, false, false, false),
('E810', 'E', 'EXPORTATION TEMPORAIRE POUR REPARATION', 'Exportation temporaire réparation', ARRAY['exportation temporaire', 'réparation'], false, false, false, false, false, false, false, false, false, false),
('E820', 'E', 'EXPORTATION TEMPORAIRE POUR DEMONSTRATION', 'Exportation temporaire démonstration', ARRAY['exportation temporaire', 'démonstration'], false, false, false, false, false, false, false, false, false, false),
('E830', 'E', 'EXPORTATION TEMPORAIRE POUR EXPOSITION NON COMMERCIALE', 'Exportation temporaire exposition', ARRAY['exportation temporaire', 'exposition'], false, false, false, false, false, false, false, false, false, false),
('E840', 'E', 'AUTRES CAS D''EXPORTATIONS TEMPORAIRES', 'Exportation temporaire autres', ARRAY['exportation temporaire', 'autres'], false, false, false, false, false, false, false, false, false, false),
('E930', 'E', 'SORTIE ZONE FRANCHE VERS L''ETRANGER', 'Export zone franche', ARRAY['exportation', 'zone franche'], false, false, false, false, false, false, false, false, false, false),
('E935', 'E', 'LIVRAISON EN ZFID PRODUITS REPRIS SUR DECRET 76.782', 'Export ZFID décret', ARRAY['exportation', 'ZFID', 'décret'], false, false, false, false, false, false, false, false, false, false),
('E950', 'E', 'Exportation de produits origine communautaire en suite EF', 'Export communautaire EF', ARRAY['exportation', 'communautaire', 'entreprise franche'], false, false, false, false, false, false, false, false, false, false),
('E951', 'E', 'EXPORTATION PRODUITS SENEGALAIS SORTIS D''ENTREPRISE FRANCHE', 'Export entreprise franche', ARRAY['exportation', 'entreprise franche', 'sénégalais'], false, false, false, false, false, false, false, false, false, false),
('E955', 'E', 'SORTIE ENTREPRISE FRANCHE EXPORTATION PRDTS EN L ETAT', 'Export EF en état', ARRAY['exportation', 'entreprise franche', 'en état'], false, false, false, false, false, false, false, false, false, false),
('E956', 'E', 'Exportation de produits nationalisés suite paiement droits', 'Export nationalisés', ARRAY['exportation', 'nationalisés'], false, false, false, false, false, false, false, false, false, false),
('E970', 'E', 'Exportation en suite d EFE de produits d origine senegalaise', 'Export EFE sénégalais', ARRAY['exportation', 'EFE', 'sénégalais'], false, false, false, false, false, false, false, false, false, false);