-- PAD-NOM-2: Idempotent migration
-- Source: PAD_2006_NOMENCLATURE_INJECTABLE_FINAL.csv (328 lines)
-- Expected net new: 324 (4 already exist)

-- 1. Extend source_type CHECK to include 'official_nomenclature'
ALTER TABLE pad_designation_aliases DROP CONSTRAINT IF EXISTS pad_designation_aliases_source_type_check;
ALTER TABLE pad_designation_aliases ADD CONSTRAINT pad_designation_aliases_source_type_check
  CHECK (source_type = ANY (ARRAY['seed'::text, 'operator_correction'::text, 'ai_suggestion_validated'::text, 'official_nomenclature'::text]));

-- 2. Create missing commodity_categories (idempotent via WHERE NOT EXISTS)
INSERT INTO commodity_categories (designation_raw, designation_normalized, pad_category, pad_category_label, confidence, evidence_level, source_documents, notes_operator, is_validated)
SELECT 'Crustacés NDA', 'Crustacés non dénommés ailleurs', 'P01', 'Crustacés non dénommés ailleurs', 0.9, 'official', ARRAY['REDEVANCES_PORTUAIRES_2006'], 'Créé par migration PAD-NOM-2 depuis barème officiel PAD 2006', true
WHERE NOT EXISTS (SELECT 1 FROM commodity_categories WHERE pad_category = 'P01');
INSERT INTO commodity_categories (designation_raw, designation_normalized, pad_category, pad_category_label, confidence, evidence_level, source_documents, notes_operator, is_validated)
SELECT 'Thonidés', 'Thonidés', 'P02', 'Thonidés', 0.9, 'official', ARRAY['REDEVANCES_PORTUAIRES_2006'], 'Créé par migration PAD-NOM-2 depuis barème officiel PAD 2006', true
WHERE NOT EXISTS (SELECT 1 FROM commodity_categories WHERE pad_category = 'P02');
INSERT INTO commodity_categories (designation_raw, designation_normalized, pad_category, pad_category_label, confidence, evidence_level, source_documents, notes_operator, is_validated)
SELECT 'Crustacés et mollusques divers', 'Crabes, crevettes, mollusques et poissons plats', 'P03', 'Crabes, crevettes, mollusques et poissons plats', 0.9, 'official', ARRAY['REDEVANCES_PORTUAIRES_2006'], 'Créé par migration PAD-NOM-2 depuis barème officiel PAD 2006', true
WHERE NOT EXISTS (SELECT 1 FROM commodity_categories WHERE pad_category = 'P03');
INSERT INTO commodity_categories (designation_raw, designation_normalized, pad_category, pad_category_label, confidence, evidence_level, source_documents, notes_operator, is_validated)
SELECT 'Petits pélagiques', 'Sardinelles, chinchard, maquereau', 'P04', 'Sardinelles, chinchard, maquereau', 0.9, 'official', ARRAY['REDEVANCES_PORTUAIRES_2006'], 'Créé par migration PAD-NOM-2 depuis barème officiel PAD 2006', true
WHERE NOT EXISTS (SELECT 1 FROM commodity_categories WHERE pad_category = 'P04');
INSERT INTO commodity_categories (designation_raw, designation_normalized, pad_category, pad_category_label, confidence, evidence_level, source_documents, notes_operator, is_validated)
SELECT 'Produits de pêche NDA', 'Produits de pêche non dénommés ailleurs', 'P05', 'Produits de pêche non dénommés ailleurs', 0.9, 'official', ARRAY['REDEVANCES_PORTUAIRES_2006'], 'Créé par migration PAD-NOM-2 depuis barème officiel PAD 2006', true
WHERE NOT EXISTS (SELECT 1 FROM commodity_categories WHERE pad_category = 'P05');
INSERT INTO commodity_categories (designation_raw, designation_normalized, pad_category, pad_category_label, confidence, evidence_level, source_documents, notes_operator, is_validated)
SELECT 'Hydrocarbures liquides et phosphates', 'Gasoil, fuel oil, diesel, butane en vrac, phosphates', 'T06', 'Gasoil, fuel oil, diesel, butane en vrac, phosphates', 0.9, 'official', ARRAY['REDEVANCES_PORTUAIRES_2006'], 'Créé par migration PAD-NOM-2 depuis barème officiel PAD 2006', true
WHERE NOT EXISTS (SELECT 1 FROM commodity_categories WHERE pad_category = 'T06');
INSERT INTO commodity_categories (designation_raw, designation_normalized, pad_category, pad_category_label, confidence, evidence_level, source_documents, notes_operator, is_validated)
SELECT 'Matières premières exportation locale', 'Attapulgite, phosphates, ferrailles, tourteaux, cellulose', 'T08', 'Attapulgite, phosphates, ferrailles, tourteaux, cellulose', 0.9, 'official', ARRAY['REDEVANCES_PORTUAIRES_2006'], 'Créé par migration PAD-NOM-2 depuis barème officiel PAD 2006', true
WHERE NOT EXISTS (SELECT 1 FROM commodity_categories WHERE pad_category = 'T08');
INSERT INTO commodity_categories (designation_raw, designation_normalized, pad_category, pad_category_label, confidence, evidence_level, source_documents, notes_operator, is_validated)
SELECT 'Sel de production locale', 'Sel de production locale', 'T10', 'Sel de production locale', 0.9, 'official', ARRAY['REDEVANCES_PORTUAIRES_2006'], 'Créé par migration PAD-NOM-2 depuis barème officiel PAD 2006', true
WHERE NOT EXISTS (SELECT 1 FROM commodity_categories WHERE pad_category = 'T10');
INSERT INTO commodity_categories (designation_raw, designation_normalized, pad_category, pad_category_label, confidence, evidence_level, source_documents, notes_operator, is_validated)
SELECT 'Pétroles et dérivés énergétiques', 'Pétrole brut, essences, bitumes, hydrocarbures raffinés', 'T11', 'Pétrole brut, essences, bitumes, hydrocarbures raffinés', 0.9, 'official', ARRAY['REDEVANCES_PORTUAIRES_2006'], 'Créé par migration PAD-NOM-2 depuis barème officiel PAD 2006', true
WHERE NOT EXISTS (SELECT 1 FROM commodity_categories WHERE pad_category = 'T11');

-- 3. Insert 328 aliases from PAD 2006 nomenclature
-- Uses ON CONFLICT DO NOTHING on unique index (normalized_term, commodity_category_id)
-- Maps pad_category -> commodity_category_id via subquery

INSERT INTO pad_designation_aliases (bl_term, normalized_term, commodity_category_id, pad_category, is_validated, source_type, source_reference)
SELECT v.bl_term, v.normalized_term,
       cc.id,
       v.pad_category,
       true,
       'official_nomenclature',
       v.source_reference
FROM (VALUES
  ('CRUSTACES NDA', 'crustaces nda', 'P01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('THONIDES', 'thonides', 'P02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('CRABES', 'crabes', 'P03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('CREVETTES DE FONDS', 'crevettes de fonds', 'P03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('MOLLUSQUES, ROUGETS, POISSONS PLATS', 'mollusques rougets poissons plats', 'P03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('MULLUSQUES, ROUGERS, POISSONS PLATS', 'mullusques rougers poissons plats', 'P03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.3, Page 24'),
  ('SARDINELLES, CHINCHARD, MAQUEREAU', 'sardinelles chinchard maquereau', 'P04', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('PRODUITS DE PECHE NDA', 'produits de peche nda', 'P05', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('APPAREILS SCIENTIFIQUES ET MATERIEL DE LABORATOIRE', 'appareils scientifiques et materiel de laboratoire', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.3, Page 24'),
  ('APPAREILS SCIENTIFIQUES ET MATERIELS DE LABORATOIRE', 'appareils scientifiques et materiels de laboratoire', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('ARMRURERIE', 'armrurerie', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('ARMURERIE', 'armurerie', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 17'),
  ('AUTRE TABAC, CIGARETTES, CIGARES, ET FILTRES', 'autre tabac cigarettes cigares et filtres', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('BIJOUTERIE SAUF BIJOUTERIE FANTAISIE', 'bijouterie sauf bijouterie fantaisie', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 17'),
  ('BOISSONS ALCOOLISEES SAUF VIN <= 13°', 'boissons alcoolisees sauf vin 13', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('CINEMA/ FILM ET APPAREIL', 'cinema film et appareil', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 18'),
  ('ELECTROPHONES, CHAINES HI-FI', 'electrophones chaines hi fi', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('HORLOGERIE', 'horlogerie', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('INSTRUMENTS DE MESURE', 'instruments de mesure', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('INSTRUMENTS DE MUSIQUE', 'instruments de musique', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 20'),
  ('MACHINE A CALCULER', 'machine a calculer', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('MACHINES A CALCULER', 'machines a calculer', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 20'),
  ('MAGNETOPHONES, MAGNETOSCOPES, TV', 'magnetophones magnetoscopes tv', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('MAT. INFORMATIQUE, ORDINATEURS', 'mat informatique ordinateurs', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 20'),
  ('MATERIEL DE PHOTOCOPIEUSE ET DE REPROGRAPHIE', 'materiel de photocopieuse et de reprographie', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('MATERIEL PHOTOGRAPHIQUE, APPAREILS PHOTOS ET PELLICULES', 'materiel photographique appareils photos et pellicules', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 20'),
  ('MATERIELS INFORMATIQUES, ORDINATEURS', 'materiels informatiques ordinateurs', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('MATERIELS PHOTOGRAPHIQUES, APPAREILS PHOTOS ET PELLICULES', 'materiels photographiques appareils photos et pellicules', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.3, Page 24'),
  ('MOBILIERS, AMEUBLEMENT', 'mobiliers ameublement', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('MONNAIE ET BILLETS DE BANQUE', 'monnaie et billets de banque', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('MUNITIONS NDA', 'munitions nda', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('MUNITIONS POUR CHASSE ET SPORT NDA, PYROTECHNIE, EXPLOISIFS', 'munitions pour chasse et sport nda pyrotechnie exploisifs', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 21'),
  ('OPTIQUE, LUNETTERIE, ARTICLES POUR FUMEURS', 'optique lunetterie articles pour fumeurs', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('PERLES, PIERRES PRECIEUX', 'perles pierres precieux', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 21'),
  ('RADIO EMETTEUR ET APARAILS METEO', 'radio emetteur et aparails meteo', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('RADIO EMETTEUR ET APPAREILS METEO', 'radio emetteur et appareils meteo', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 22'),
  ('TABAC EN FEUILLE (MAT 1 ére)', 'tabac en feuille mat 1 ere', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('TELEPHONE ET ACCESSOIRES', 'telephone et accessoires', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('TELEVISIONS ET ACCESSOIRES', 'televisions et accessoires', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('VIN ET BOISSONS ALCOOLISEES > 13°', 'vin et boissons alcoolisees 13', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.3, Page 24'),
  ('VINS < = 13° NDA', 'vins 13 nda', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('VINS ET BOISSONS ALCOOLISEES >13°', 'vins et boissons alcoolisees 13', 'T01', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 23'),
  ('ANIMAUX VIVANTS', 'animaux vivants', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('APPAREIL ELECTRO-MENAGERS ET CLIMATISEURS', 'appareil electro menagers et climatiseurs', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('APPAREILS ELECTRO-MENAGERS ET CLIMATISEURS', 'appareils electro menagers et climatiseurs', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 17'),
  ('APPAREILS MENAGERS NON ELECTRIQUES', 'appareils menagers non electriques', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('ARTICLES MAT. PECHE & CHASSE', 'articles mat peche chasse', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('ARTICLES METALLIQUES NDA', 'articles metalliques nda', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('AVITAILLEMENTS HOTEL', 'avitaillements hotel', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('BAGAGES, EFFETS PERSONNELS', 'bagages effets personnels', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('BANANES', 'bananes', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('BEURRE FROAMGE ET AUTRES PRODUITS LAITIERS NDA', 'beurre froamge et autres produits laitiers nda', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('BEURRE FROMAGE ET AUTRES PRODUITS LAITIERS NDA', 'beurre fromage et autres produits laitiers nda', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.3, Page 25'),
  ('BICYCLETTES ET ACCESSOIRES', 'bicyclettes et accessoires', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('BONNERIE, MERCERIE', 'bonnerie mercerie', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('CABLES ELECTRONIQUES', 'cables electroniques', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('CACAO, CHOCOLAT, CHICOREE', 'cacao chocolat chicoree', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('CAFE, NESCAFE', 'cafe nescafe', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('CHAUSSURES', 'chaussures', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('COLAS', 'colas', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('CONDIMENT, EPICE, AROMES NATURELS OU ARTIFICIELS NDA', 'condiment epice aromes naturels ou artificiels nda', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('CONDIMENTS, EPICE, AROMES NATURELS OU ARTIFICIELS NDA', 'condiments epice aromes naturels ou artificiels nda', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 18'),
  ('CONFITURE', 'confiture', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('CONSERVES DE FRUITS', 'conserves de fruits', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('CONSERVES DE LEGUMES', 'conserves de legumes', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('CONSERVES DE POISSON CRUSTACES ET MOLLUSQUES NDA', 'conserves de poisson crustaces et mollusques nda', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('CONSERVES DE VIANDE, ET CHARCUTERIE', 'conserves de viande et charcuterie', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('COUTELLERIE', 'coutellerie', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('COUVERTURE, LINGERIE', 'couverture lingerie', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('DROGUERIE, PRODUITS D''ENTRETIEN', 'droguerie produits d entretien', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 19'),
  ('DROGUERIES, PRODUITS D''ENTRETIEN', 'drogueries produits d entretien', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('EFFETS DE TOILETTE', 'effets de toilette', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 19'),
  ('ELEMENTS DE CONSTRUCTION FINIS ET CONSTRUCTIONS EN METAL', 'elements de construction finis et constructions en metal', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('EXTINCTEURS, BOUTEILLES DE GAZ (vides ou pleines)', 'extincteurs bouteilles de gaz vides ou pleines', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('LEGUMES FRAIS NDA', 'legumes frais nda', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('LIVRES, JOURNAUX, IMPRIMES', 'livres journaux imprimes', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('MACHINES OUTILS', 'machines outils', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('MAROQUINERIE', 'maroquinerie', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('MATERIEL DE PHOTOCOPIE ET DE REPROGRAPHIE', 'materiel de photocopie et de reprographie', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 20'),
  ('MATERIELS ELECTRIQUES ET APPAREIL ECLAIRAGE', 'materiels electriques et appareil eclairage', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('MATERIELS INDUSTRIEL NDA', 'materiels industriel nda', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.3, Page 25'),
  ('MATERIELS INDUSTRIELS NDA', 'materiels industriels nda', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('MIROITERIE', 'miroiterie', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('MOTEURS ELCETRIQUES ET A EXPLOSION', 'moteurs elcetriques et a explosion', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('MOTOCYCLES SAUF SCOOOTER', 'motocycles sauf scoooter', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('OBJET ART, COLLECTION', 'objet art collection', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 21'),
  ('ORANGES', 'oranges', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('OUTILS A MAIN', 'outils a main', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('PAPETERIE, ET MATERIELS, FOURNITURE DE BUREAU', 'papeterie et materiels fourniture de bureau', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('PAPETERIRE, MATERIELS FOURNITURE DE BUREAU', 'papeterire materiels fourniture de bureau', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.3, Page 25'),
  ('PAPETERIRE, MATERIELS FOURNITURES DE BUREAU', 'papeterire materiels fournitures de bureau', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 21'),
  ('PARFUMERIE, TEINTURE CAPILAIRE', 'parfumerie teinture capilaire', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 21'),
  ('PARFUMERIE, TEINTURE CAPILLAIRE', 'parfumerie teinture capillaire', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('PATE ET PREPARATION ALIMENTAIRES A BASE DE PATE', 'pate et preparation alimentaires a base de pate', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('PEINTURE, COLORANTS INDUSTRIELS RESINE POUR PEINTURE', 'peinture colorants industriels resine pour peinture', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('PIECES DETACHEES DE MACHINES ET APPAREILS', 'pieces detachees de machines et appareils', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('PIECES DETACHEES DE VEHICULES ET DE MATERIEL DE TRANSPORT', 'pieces detachees de vehicules et de materiel de transport', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('PLATS CUISINES', 'plats cuisines', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('PLOMBERIE, ROBINETTERIE', 'plomberie robinetterie', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('PNEUMATIQUES', 'pneumatiques', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('POMMES', 'pommes', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('PREPARATIONS ALIMENTAIRES NDA', 'preparations alimentaires nda', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('PRODUITS COSMETIQUES', 'produits cosmetiques', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('PRODUITS DE TOILETTE NDA', 'produits de toilette nda', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('PRODUITS METALLURGIQUES NON FERREUX', 'produits metallurgiques non ferreux', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 12'),
  ('QUINCAILLERIE, BOULONNERIE, VISSERIE', 'quincaillerie boulonnerie visserie', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('QUINCALLERIE, BOULONNERIE, VISSERIE', 'quincallerie boulonnerie visserie', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 22'),
  ('SACS ET COLIS POSTAUX', 'sacs et colis postaux', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('SCOOTERS', 'scooters', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('SEL NDA', 'sel nda', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 12'),
  ('SIMILI- CUIRS', 'simili cuirs', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('TEINTURE NDA', 'teinture nda', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('TEINTURES NDA', 'teintures nda', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 23'),
  ('TEXTILE, HABILLEMENT, LINGE DE MAISON NDA', 'textile habillement linge de maison nda', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('THE', 'the', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('TISSUS, ETOFFES', 'tissus etoffes', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('USTENSILES DE MENAGE', 'ustensiles de menage', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('USTENSILS DE MENAGE', 'ustensils de menage', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 23'),
  ('VAISSELLES, VERRERIE DE TABLE', 'vaisselles verrerie de table', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('VEHICULES ROULIER < 1,5 T', 'vehicules roulier 1 5 t', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('VEHICULES ROULIER > 2,5 T', 'vehicules roulier 2 5 t', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('VERNIS, DILUANT, SOLVANT, COLORANT', 'vernis diluant solvant colorant', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('VERRE A VITRE ET AUTRE VERRE PLAT', 'verre a vitre et autre verre plat', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('VETEMENTS NEUFS', 'vetements neufs', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('VIANDE FRAICHE OU CONGELEE', 'viande fraiche ou congelee', 'T02', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('ACIDE GRAS', 'acide gras', 'T03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('CONSERVE DE THON ET PICHARDS', 'conserve de thon et pichards', 'T03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('CONSERVES DE THON ET PICHARDS', 'conserves de thon et pichards', 'T03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 18'),
  ('CUIRS ET PEAUX BRUTES', 'cuirs et peaux brutes', 'T03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('CUIRS ET PEAUX BRUTS', 'cuirs et peaux bruts', 'T03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.3, Page 26'),
  ('FARINE LACTEE', 'farine lactee', 'T03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('FARINES LACTEE', 'farines lactee', 'T03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 19'),
  ('GLUCERINE BRUTE', 'glucerine brute', 'T03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 20'),
  ('GLUCOSE C6, H12 06 ET AUTRES', 'glucose c6 h12 06 et autres', 'T03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('GLYCERINE BRUTE', 'glycerine brute', 'T03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('HUILES BRUTES VEGETALES OU ANIMALES POUR LA SAVONNERIE', 'huiles brutes vegetales ou animales pour la savonnerie', 'T03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('HUILES BRUTES VEGETALES OU ANIMALES POUR LA SAVONNERIRE', 'huiles brutes vegetales ou animales pour la savonnerire', 'T03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 20'),
  ('HUILES COMESTIBLES EN VRAC NDA', 'huiles comestibles en vrac nda', 'T03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('MATIERE PLASTIQUE BRUTE NDA', 'matiere plastique brute nda', 'T03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('MATIERES PLASTIQUES BRUTES NDA', 'matieres plastiques brutes nda', 'T03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 21'),
  ('PRODUITS BRUTS D''ORIGINE ANIMALE ET VEGETALE NDA', 'produits bruts d origine animale et vegetale nda', 'T03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 22'),
  ('PRODUITS BRUTS D''ORIGINE VEGETAL ET VEGETALE NDA', 'produits bruts d origine vegetal et vegetale nda', 'T03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('SOUDE CAUSTIQUE', 'soude caustique', 'T03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('SOUFFRE NDA', 'souffre nda', 'T03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 12'),
  ('SOUFRE NDA', 'soufre nda', 'T03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 22'),
  ('SUCRE BRUT ET GRANULE DE SUCRE', 'sucre brut et granule de sucre', 'T03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('SUCRE RAFFINE EN MORCEUAX OU EN POUDRE', 'sucre raffine en morceuax ou en poudre', 'T03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('SUIF', 'suif', 'T03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('TALL- OIL', 'tall oil', 'T03', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('BOIS DEBITES, SCIAGES, TRAVERSES', 'bois debites sciages traverses', 'T04', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('BOIS EN GRUMES', 'bois en grumes', 'T04', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('BOIS TRAVAILLES, CONTRE PLAQUES, PLAQUAGES', 'bois travailles contre plaques plaquages', 'T04', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('BOISSONS NON ALCOOLISEES', 'boissons non alcoolisees', 'T04', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 18'),
  ('BOISSONS NON ALCOOLISEES NDA', 'boissons non alcoolisees nda', 'T04', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('CONFISERIE, BONBONS ET SUCRERIES NDA', 'confiserie bonbons et sucreries nda', 'T04', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('EAU MINERALE ET NATURELLE', 'eau minerale et naturelle', 'T04', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('ENGRAIS NATURELS', 'engrais naturels', 'T04', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 13'),
  ('ENGRAIS NDA', 'engrais nda', 'T04', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 13'),
  ('FRIPPERIES ET VETEMENTS USAGERS', 'fripperies et vetements usagers', 'T04', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('GLACES ET SOBRETS', 'glaces et sobrets', 'T04', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('GLACES ET SORBETS', 'glaces et sorbets', 'T04', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.3, Page 27'),
  ('JUS DE FRUIT, CONCENTRE DE JUS', 'jus de fruit concentre de jus', 'T04', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('JUS DE FRUIT ET NATURELLE', 'jus de fruit et naturelle', 'T04', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 20'),
  ('LAIT EN POUDRE', 'lait en poudre', 'T04', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('MIEL', 'miel', 'T04', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('OIGNONS COMESTIBLES', 'oignons comestibles', 'T04', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('POISSONS SALES SECHES', 'poissons sales seches', 'T04', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('POMME DE TERRE ET SEMENCE DE POMME DE TERRE', 'pomme de terre et semence de pomme de terre', 'T04', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 22'),
  ('POMME DE TERRE ET SEMENCES DE POMME DE TERRE', 'pomme de terre et semences de pomme de terre', 'T04', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('PORDUITS PHARMACEUTIQUES, MEDICAMENTS', 'porduits pharmaceutiques medicaments', 'T04', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('POTASSE NDA', 'potasse nda', 'T04', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 13'),
  ('ACIDE PHOSPHORIQUE ICS', 'acide phosphorique ics', 'T05', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('BLE (WHEAT ANGLAIS)', 'ble wheat anglais', 'T05', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('CÉRÉALES NDA', 'cereales nda', 'T05', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('CIMENT', 'ciment', 'T05', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 13'),
  ('ENGRAIS ICS', 'engrais ics', 'T05', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 13'),
  ('HOUBLON, GRUAUX, MALT', 'houblon gruaux malt', 'T05', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('MAIS ET FARINE DE MAIS', 'mais et farine de mais', 'T05', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('MIL, SORGO', 'mil sorgo', 'T05', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('PLATRE EN SAC', 'platre en sac', 'T05', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 13'),
  ('POTASSE ICS', 'potasse ics', 'T05', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 13'),
  ('PRODUITS ICS NDA', 'produits ics nda', 'T05', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 13'),
  ('RIZ', 'riz', 'T05', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('SOUFFRE ICS', 'souffre ics', 'T05', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 12'),
  ('SOUFRE ICS', 'soufre ics', 'T05', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 22'),
  ('AMONIAC', 'amoniac', 'T06', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('BUTANE EN VRAC', 'butane en vrac', 'T06', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('DIESEL OIL', 'diesel oil', 'T06', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('FUEL OIL', 'fuel oil', 'T06', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('GASOIL', 'gasoil', 'T06', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('PHOSPHATES D''ALLUMINE', 'phosphates d allumine', 'T06', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 21'),
  ('PHOSPHATES D''ALUMINE', 'phosphates d alumine', 'T06', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 13'),
  ('PHOSPHATES DE CALCIUM', 'phosphates de calcium', 'T06', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 13'),
  ('ALIMENT DE BETAIL, SON ET TOURTERAUX NDA', 'aliment de betail son et tourteraux nda', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('AMIANTE', 'amiante', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 13'),
  ('ARACHIDES DECORTIQUEES', 'arachides decortiquees', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('ARGILE ET CRAIE EN POUDRE', 'argile et craie en poudre', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 12'),
  ('AUTRES MATIERES TEXTILES NDA', 'autres matieres textiles nda', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('CHARBON', 'charbon', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 18'),
  ('CHARBON DE TERRE', 'charbon de terre', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('CHAUX ETEINTE', 'chaux eteinte', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 13'),
  ('CHIFFONS ET DECHETS DE TEXTILES', 'chiffons et dechets de textiles', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('CLINKER', 'clinker', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 13'),
  ('COKE', 'coke', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('COTON EGRENE EN BALLE OU BIG BAG', 'coton egrene en balle ou big bag', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('FARINE DE BLE', 'farine de ble', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('FARINE DE POISSON', 'farine de poisson', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('GRAINES DE TOURNESOL ET GRAINES OLEAGINEUX NDA', 'graines de tournesol et graines oleagineux nda', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('GRAINES ET SEMENCES NDA (sauf semences de pom.de terres)', 'graines et semences nda sauf semences de pom de terres', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 20'),
  ('GRAINES ET SEMENCES NDA (sauf semences de pomme de terres)', 'graines et semences nda sauf semences de pomme de terres', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.3, Page 28'),
  ('GRAINES ET SEMENCES NDA (sauf semences de pommes de terres)', 'graines et semences nda sauf semences de pommes de terres', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('GYPSE', 'gypse', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 13'),
  ('MELASSE DE CANNE', 'melasse de canne', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('MINERAIS BRUTS', 'minerais bruts', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 12'),
  ('SABLE, PIERRES DE CONSTRUCTION', 'sable pierres de construction', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 12'),
  ('SABLE, PIERRES DE CONSTRUCTIONS', 'sable pierres de constructions', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.3, Page 28'),
  ('SEMOULE ET AUTRES FARINE DE CERALES NDA', 'semoule et autres farine de cerales nda', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('SEMOULE ET AUTRES FARINES DE CERALES NDA', 'semoule et autres farines de cerales nda', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 22'),
  ('TERRES REFRACRTAIRE', 'terres refracrtaire', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.3, Page 28'),
  ('TERRES REFRACRTAIRES', 'terres refracrtaires', 'T07', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 13'),
  ('ATTAPULGITE', 'attapulgite', 'T08', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 12'),
  ('CELLULOSE ET PATE A PAPIER', 'cellulose et pate a papier', 'T08', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('DECHET DE PAPIER ET VIEUX JOURNAUX', 'dechet de papier et vieux journaux', 'T08', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('FERAILLES HORS USAGE', 'ferailles hors usage', 'T08', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 12'),
  ('PHOSPHATES NDA', 'phosphates nda', 'T08', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 13'),
  ('PHOSPHATES ORIGINE LOCALE NDA', 'phosphates origine locale nda', 'T08', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 13'),
  ('TOURTEREAUX D''ARACHIDE', 'tourtereaux d arachide', 'T08', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('AVION, HELICOPTERE, EMBARCATION', 'avion helicoptere embarcation', 'T09', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('MATERIEL DE CHANTIER', 'materiel de chantier', 'T09', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('TRACTEURS AGRICOLES', 'tracteurs agricoles', 'T09', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('VEHICULE ET MATERIEL DE TRANSPORT NDA', 'vehicule et materiel de transport nda', 'T09', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('VEHICULES DE CHANTIER ET VEHICULES INDUSTRIELS', 'vehicules de chantier et vehicules industriels', 'T09', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('VEHICULES ROULIER DE 1,5 A 2,5 T', 'vehicules roulier de 1 5 a 2 5 t', 'T09', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('VEHICULES ROUTIER DE 1,5 A 2,5 T', 'vehicules routier de 1 5 a 2 5 t', 'T09', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 23'),
  ('SEL DE PRODUCTION LOCALE', 'sel de production locale', 'T10', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 12'),
  ('BASE PARFUM', 'base parfum', 'T11', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('BITUMES EN FUITS, EN SAC', 'bitumes en fuits en sac', 'T11', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 12'),
  ('BITUMES EN FUTS, EN SAC', 'bitumes en futs en sac', 'T11', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 18'),
  ('BITUMES EN VRAC', 'bitumes en vrac', 'T11', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 12'),
  ('DECHETS NON FERREUX', 'dechets non ferreux', 'T11', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 12'),
  ('ESSENCE AUTO', 'essence auto', 'T11', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('ESSENCE AVION', 'essence avion', 'T11', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('HYDROCARBURES RAFFINEES NDA', 'hydrocarbures raffinees nda', 'T11', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('PETROLE BRUT', 'petrole brut', 'T11', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('PETROLE LAMPANT', 'petrole lampant', 'T11', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('PRODUITS ENERGITIQUES GAZEUX NDA', 'produits energitiques gazeux nda', 'T11', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 22'),
  ('PRODUITS NERGITIQUES GAZEUX NDA', 'produits nergitiques gazeux nda', 'T11', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('ACIDE NDA', 'acide nda', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('ACIDE PHOSPHORIQUE NDA', 'acide phosphorique nda', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('ALCCOL INDUSTRIEL', 'alccol industriel', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('AMIDON', 'amidon', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('ARTICLES DE MANUFACTURES NDA', 'articles de manufactures nda', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 17'),
  ('ARTICLES DE PUBLICITE SAUF PAPIER IMPRIME', 'articles de publicite sauf papier imprime', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('ARTICLES EN MATIERES PLASTIQUES NDA', 'articles en matieres plastiques nda', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 17'),
  ('ARTICLES EN MATIERES PLASTIQUES NENDA', 'articles en matieres plastiques nenda', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.3, Page 29'),
  ('AUTRES PRODUITS MINERAUX', 'autres produits mineraux', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 17'),
  ('AUTRES PRODUITS MINERAUX NDA', 'autres produits mineraux nda', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 12'),
  ('BEURRE DE KARITE', 'beurre de karite', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('BEURRES DE KARITE', 'beurres de karite', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 17'),
  ('BEURRES VEGETALES ET MARGARINES', 'beurres vegetales et margarines', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 17'),
  ('BEURRES VEGETAUX ET MARGARINES', 'beurres vegetaux et margarines', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('BIJOUTERIE FANTAISIE (SANS PIERRES NI METAUX PRECIEUX)', 'bijouterie fantaisie sans pierres ni metaux precieux', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 17'),
  ('BISCUITS', 'biscuits', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('BLEU D''OUTRE MER', 'bleu d outre mer', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('BOUCHONS ET CAPSULES', 'bouchons et capsules', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('BRIQUES REFRACTAIRES', 'briques refractaires', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 13'),
  ('CAOUTCHOUC NATUREL', 'caoutchouc naturel', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('CAOUTCHOUC PLAQUE OU ROULEAUX', 'caoutchouc plaque ou rouleaux', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 18'),
  ('CAOUTCHOUC PLAQUES OU ROULEAUX', 'caoutchouc plaques ou rouleaux', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('CARTONNAGE EN ROULEAU OU EN PLAQUE', 'cartonnage en rouleau ou en plaque', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('CARTONNAGE EN ROULEAU OU NE PLAQUE', 'cartonnage en rouleau ou ne plaque', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 18'),
  ('CHAUFFE EAU ET MATERIELS DE CHAUFFAGE', 'chauffe eau et materiels de chauffage', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 18'),
  ('CHAUFFE EEAU ET MATERIELS DE CHAUFFAGE', 'chauffe eeau et materiels de chauffage', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('CHAUX VIVE', 'chaux vive', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 13'),
  ('CHLORURE DE POTASSIUM', 'chlorure de potassium', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 13'),
  ('CIRE, CIRAGE', 'cire cirage', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('COFFRE – FORT', 'coffre fort', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 18'),
  ('CORDES, CORDAGES FICELLES', 'cordes cordages ficelles', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('CUIRS ET PEAUX TRAVAILLEES SAUF MAROQUINERIE', 'cuirs et peaux travaillees sauf maroquinerie', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 19'),
  ('CUIRS ET PEAUX TRAVAILLES SAUF MAROQUINERIE', 'cuirs et peaux travailles sauf maroquinerie', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('EMBALLAGES VIDES EN CARTON', 'emballages vides en carton', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('FILS ET MATIERES TEXTILES NATURELLES OU ARTIFICIELLES NDA', 'fils et matieres textiles naturelles ou artificielles nda', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('FRUITS FRAIS NDA', 'fruits frais nda', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('FRUITS SECS', 'fruits secs', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('GOMMES VEGETAL', 'gommes vegetal', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 20'),
  ('GOMMES VEGETALES', 'gommes vegetales', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('HEXANE', 'hexane', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('HUILES COMESTIBLES EMBALLEES NDA', 'huiles comestibles emballees nda', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('HUILES DE GRAISSAGE ET AUTRES HUILES INDUSTRIELLES NDA', 'huiles de graissage et autres huiles industrielles nda', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 12'),
  ('HUILES DE GRAISSAGE ET AUTRESHUILES INDUSTRIELLES NDA', 'huiles de graissage et autreshuiles industrielles nda', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.3, Page 29'),
  ('INSECTICIDES, PESTICIDES', 'insecticides pesticides', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('LEGUMES SECS', 'legumes secs', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 9'),
  ('LEVURES', 'levures', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('MACHINES AGRICOLES', 'machines agricoles', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('MATERIAUX DE CONSTRUCTION ET CARRELAGE NDA', 'materiaux de construction et carrelage nda', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 13'),
  ('MATERIEL SANITAIRE EN FAIENCE, PORCELAINE', 'materiel sanitaire en faience porcelaine', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('MATIERES CHIMIQUES NDA', 'matieres chimiques nda', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.3, Page 29'),
  ('MATIRES CHIMIQUES NDA', 'matires chimiques nda', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('NEUTRAL SOLVANT', 'neutral solvant', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('PAPIER BITUME', 'papier bitume', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('PAPIER ET PAPIER KRAFT EN BOBINES > 1T', 'papier et papier kraft en bobines 1t', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('PAPIER ET PAPIER KRAFT EN BOBINNES > 1T', 'papier et papier kraft en bobinnes 1t', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 21'),
  ('PARAFFINE', 'paraffine', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 21'),
  ('PARAFINE', 'parafine', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('PRODUIT CHIMIQUE DE BASE NDA', 'produit chimique de base nda', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('PRODUITS CHIMIQUES DE BASE NDA', 'produits chimiques de base nda', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.3, Page 30'),
  ('QUINOUELIBA', 'quinoueliba', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 10'),
  ('QUINQUELIBA', 'quinqueliba', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 22'),
  ('RECIPIENT VIDE EN VERRE, EN BOIS OU EN FER NDA', 'recipient vide en verre en bois ou en fer nda', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('RESINE SYNTHETIQUE', 'resine synthetique', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('REVETEMENT DE SOL (CARRELAGE) NDA', 'revetement de sol carrelage nda', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 22'),
  ('SACS EN JUT OU EN FIBRES VEGETALES', 'sacs en jut ou en fibres vegetales', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('SACS EN JUTE OU EN FIBRES VEGETALES', 'sacs en jute ou en fibres vegetales', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 22'),
  ('SACS EN JUTE OU EN FIBRES VEGETALS', 'sacs en jute ou en fibres vegetals', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.3, Page 30'),
  ('SACS EN PROPYLENE', 'sacs en propylene', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('SAVONS ORDINAIRES', 'savons ordinaires', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('SOLVESSO', 'solvesso', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('TALC', 'talc', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 12'),
  ('TOLES ET PRODUITS LAMINES, FIL DE FER, RAILS, PROFILES ET FER A BETON', 'toles et produits lamines fil de fer rails profiles et fer a beton', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 12'),
  ('TOLUENE', 'toluene', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 14'),
  ('TRANSACTIONS SPECIALES NDA', 'transactions speciales nda', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 16'),
  ('TUBES, TUYAUX ET POTEAUX METALLIQUES ET PRODUITS FERREUX NDA', 'tubes tuyaux et poteaux metalliques et produits ferreux nda', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 12'),
  ('TUYEAUX EN PVC', 'tuyeaux en pvc', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 23'),
  ('ŒUVRES ET OBJETS D''ART', 'uvres et objets d art', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.2, Page 21'),
  ('VERRE, PRODUITS CERAMIQUES NDA', 'verre produits ceramiques nda', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 15'),
  ('WHITE SPIRIT', 'white spirit', 'T12', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 11'),
  ('CONTENEURS DE GROUPAGE IMPORT DE DIVERSES MARCHANDISES NE CONTENANT AUCUN PRODUIT DE CAT. T01', 'conteneurs de groupage import de diverses marchandises ne contenant aucun produit de cat t01', 'T13', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.3, Page 30'),
  ('FIL MACHINE, BOBINE DE TOLES, FEUILLARD, FER BLANC', 'fil machine bobine de toles feuillard fer blanc', 'T14', 'REDEVANCES_PORTUAIRES_2006.pdf, Section 2.3.1, Page 12')
) AS v(bl_term, normalized_term, pad_category, source_reference)
JOIN commodity_categories cc ON cc.pad_category = v.pad_category
ON CONFLICT (normalized_term, commodity_category_id) DO NOTHING;